// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    /// <summary>
    /// `duplocloud.AwsEfsLifecyclePolicy` Provides an Elastic File System (EFS) File System Lifecycle Policy resource in DuploCloud.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Duplocloud = Pulumi.Duplocloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var myapp = new Duplocloud.Tenant("myapp", new()
    ///     {
    ///         AccountName = "myapp",
    ///         PlanId = "default",
    ///     });
    /// 
    ///     var efs = new Duplocloud.AwsEfsFileSystem("efs", new()
    ///     {
    ///         TenantId = myapp.TenantId,
    ///         Name = "efs-test",
    ///         PerformanceMode = "generalPurpose",
    ///         ThroughputMode = "elastic",
    ///         Backup = true,
    ///         Encrypted = true,
    ///     });
    /// 
    ///     var efsPolicy = new Duplocloud.AwsEfsLifecyclePolicy("efs_policy", new()
    ///     {
    ///         TenantId = myapp.TenantId,
    ///         FileSystemId = efs.FileSystemId,
    ///         LifecyclePolicies = new[]
    ///         {
    ///             new Duplocloud.Inputs.AwsEfsLifecyclePolicyLifecyclePolicyArgs
    ///             {
    ///                 TransitionToIa = "AFTER_7_DAYS",
    ///             },
    ///             new Duplocloud.Inputs.AwsEfsLifecyclePolicyLifecyclePolicyArgs
    ///             {
    ///                 TransitionToArchive = "AFTER_14_DAYS",
    ///             },
    ///             new Duplocloud.Inputs.AwsEfsLifecyclePolicyLifecyclePolicyArgs
    ///             {
    ///                 TransitionToPrimaryStorageClass = "AFTER_1_ACCESS",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Example: Importing an existing AWS Elastic File System
    /// 
    ///  - *TENANT_ID* is the tenant GUID
    /// 
    ///  - *FILE_SYSTEM_ID* is the ID of the AWS Elastic File System
    /// 
    /// # 
    /// 
    /// ```sh
    /// $ pulumi import duplocloud:index/awsEfsLifecyclePolicy:AwsEfsLifecyclePolicy efslifecycle *TENANT_ID*/*FILE_SYSTEM_ID*
    /// ```
    /// </summary>
    [PulumiResourceType("duplocloud:index/awsEfsLifecyclePolicy:AwsEfsLifecyclePolicy")]
    public partial class AwsEfsLifecyclePolicy : global::Pulumi.CustomResource
    {
        [Output("fileSystemId")]
        public Output<string> FileSystemId { get; private set; } = null!;

        [Output("lifecyclePolicies")]
        public Output<ImmutableArray<Outputs.AwsEfsLifecyclePolicyLifecyclePolicy>> LifecyclePolicies { get; private set; } = null!;

        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;


        /// <summary>
        /// Create a AwsEfsLifecyclePolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AwsEfsLifecyclePolicy(string name, AwsEfsLifecyclePolicyArgs args, CustomResourceOptions? options = null)
            : base("duplocloud:index/awsEfsLifecyclePolicy:AwsEfsLifecyclePolicy", name, args ?? new AwsEfsLifecyclePolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AwsEfsLifecyclePolicy(string name, Input<string> id, AwsEfsLifecyclePolicyState? state = null, CustomResourceOptions? options = null)
            : base("duplocloud:index/awsEfsLifecyclePolicy:AwsEfsLifecyclePolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/duplocloud/pulumi-duplocloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AwsEfsLifecyclePolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AwsEfsLifecyclePolicy Get(string name, Input<string> id, AwsEfsLifecyclePolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new AwsEfsLifecyclePolicy(name, id, state, options);
        }
    }

    public sealed class AwsEfsLifecyclePolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("fileSystemId", required: true)]
        public Input<string> FileSystemId { get; set; } = null!;

        [Input("lifecyclePolicies", required: true)]
        private InputList<Inputs.AwsEfsLifecyclePolicyLifecyclePolicyArgs>? _lifecyclePolicies;
        public InputList<Inputs.AwsEfsLifecyclePolicyLifecyclePolicyArgs> LifecyclePolicies
        {
            get => _lifecyclePolicies ?? (_lifecyclePolicies = new InputList<Inputs.AwsEfsLifecyclePolicyLifecyclePolicyArgs>());
            set => _lifecyclePolicies = value;
        }

        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public AwsEfsLifecyclePolicyArgs()
        {
        }
        public static new AwsEfsLifecyclePolicyArgs Empty => new AwsEfsLifecyclePolicyArgs();
    }

    public sealed class AwsEfsLifecyclePolicyState : global::Pulumi.ResourceArgs
    {
        [Input("fileSystemId")]
        public Input<string>? FileSystemId { get; set; }

        [Input("lifecyclePolicies")]
        private InputList<Inputs.AwsEfsLifecyclePolicyLifecyclePolicyGetArgs>? _lifecyclePolicies;
        public InputList<Inputs.AwsEfsLifecyclePolicyLifecyclePolicyGetArgs> LifecyclePolicies
        {
            get => _lifecyclePolicies ?? (_lifecyclePolicies = new InputList<Inputs.AwsEfsLifecyclePolicyLifecyclePolicyGetArgs>());
            set => _lifecyclePolicies = value;
        }

        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        public AwsEfsLifecyclePolicyState()
        {
        }
        public static new AwsEfsLifecyclePolicyState Empty => new AwsEfsLifecyclePolicyState();
    }
}
