// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    /// <summary>
    /// `duplocloud.AzureTenantKeyVault` manages a azure Key Vault in DuploCloud.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Duplocloud = DuploCloud.Pulumi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var tenant = new Duplocloud.Tenant("tenant", new()
    ///     {
    ///         AccountName = "test",
    ///         PlanId = "test",
    ///     });
    /// 
    ///     var kv = new Duplocloud.AzureTenantKeyVault("kv", new()
    ///     {
    ///         TenantId = tenant.TenantId,
    ///         Name = "tst-kv001",
    ///         SkuName = "standard",
    ///         PurgeProtectionEnabled = true,
    ///         SoftDeleteRetentionDays = 90,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Example: Importing an existing Azure Tenant Key Vault
    /// 
    ///  - *TENANT_ID* is the tenant GUID
    /// 
    ///  - *VAULT_NAME* is the short name of the Azure Tenant Key Vault
    /// 
    /// # 
    /// 
    /// ```sh
    /// $ pulumi import duplocloud:index/azureTenantKeyVault:AzureTenantKeyVault kv *TENANT_ID*/*VAULT_NAME*
    /// ```
    /// </summary>
    [PulumiResourceType("duplocloud:index/azureTenantKeyVault:AzureTenantKeyVault")]
    public partial class AzureTenantKeyVault : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The azure ID of the Key Vault.
        /// </summary>
        [Output("azureId")]
        public Output<string> AzureId { get; private set; } = null!;

        /// <summary>
        /// Azure Disk Encryption is permitted to retrieve secrets from the vault and unwrap keys.
        /// </summary>
        [Output("enabledForDiskEncryption")]
        public Output<bool> EnabledForDiskEncryption { get; private set; } = null!;

        /// <summary>
        /// Specifies the name of the Key Vault.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Is Purge Protection enabled for this Key Vault?
        /// </summary>
        [Output("purgeProtectionEnabled")]
        public Output<bool> PurgeProtectionEnabled { get; private set; } = null!;

        /// <summary>
        /// The Name of the SKU used for this Key Vault. Possible values are `standard` and `premium`.
        /// </summary>
        [Output("skuName")]
        public Output<string> SkuName { get; private set; } = null!;

        /// <summary>
        /// The number of days that items should be retained for once soft-deleted. This value can be between `7` and `90` (the default) days. Defaults to `90`.
        /// </summary>
        [Output("softDeleteRetentionDays")]
        public Output<int?> SoftDeleteRetentionDays { get; private set; } = null!;

        /// <summary>
        /// The GUID of the DuploCloud tenant that the key vault will be created in.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        /// <summary>
        /// The URI of the Key Vault, used for performing operations on keys and secrets.
        /// </summary>
        [Output("vaultUri")]
        public Output<string> VaultUri { get; private set; } = null!;


        /// <summary>
        /// Create a AzureTenantKeyVault resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AzureTenantKeyVault(string name, AzureTenantKeyVaultArgs args, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureTenantKeyVault:AzureTenantKeyVault", name, args ?? new AzureTenantKeyVaultArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AzureTenantKeyVault(string name, Input<string> id, AzureTenantKeyVaultState? state = null, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureTenantKeyVault:AzureTenantKeyVault", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/duplocloud/pulumi-duplocloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AzureTenantKeyVault resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AzureTenantKeyVault Get(string name, Input<string> id, AzureTenantKeyVaultState? state = null, CustomResourceOptions? options = null)
        {
            return new AzureTenantKeyVault(name, id, state, options);
        }
    }

    public sealed class AzureTenantKeyVaultArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the name of the Key Vault.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Is Purge Protection enabled for this Key Vault?
        /// </summary>
        [Input("purgeProtectionEnabled")]
        public Input<bool>? PurgeProtectionEnabled { get; set; }

        /// <summary>
        /// The Name of the SKU used for this Key Vault. Possible values are `standard` and `premium`.
        /// </summary>
        [Input("skuName", required: true)]
        public Input<string> SkuName { get; set; } = null!;

        /// <summary>
        /// The number of days that items should be retained for once soft-deleted. This value can be between `7` and `90` (the default) days. Defaults to `90`.
        /// </summary>
        [Input("softDeleteRetentionDays")]
        public Input<int>? SoftDeleteRetentionDays { get; set; }

        /// <summary>
        /// The GUID of the DuploCloud tenant that the key vault will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public AzureTenantKeyVaultArgs()
        {
        }
        public static new AzureTenantKeyVaultArgs Empty => new AzureTenantKeyVaultArgs();
    }

    public sealed class AzureTenantKeyVaultState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The azure ID of the Key Vault.
        /// </summary>
        [Input("azureId")]
        public Input<string>? AzureId { get; set; }

        /// <summary>
        /// Azure Disk Encryption is permitted to retrieve secrets from the vault and unwrap keys.
        /// </summary>
        [Input("enabledForDiskEncryption")]
        public Input<bool>? EnabledForDiskEncryption { get; set; }

        /// <summary>
        /// Specifies the name of the Key Vault.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Is Purge Protection enabled for this Key Vault?
        /// </summary>
        [Input("purgeProtectionEnabled")]
        public Input<bool>? PurgeProtectionEnabled { get; set; }

        /// <summary>
        /// The Name of the SKU used for this Key Vault. Possible values are `standard` and `premium`.
        /// </summary>
        [Input("skuName")]
        public Input<string>? SkuName { get; set; }

        /// <summary>
        /// The number of days that items should be retained for once soft-deleted. This value can be between `7` and `90` (the default) days. Defaults to `90`.
        /// </summary>
        [Input("softDeleteRetentionDays")]
        public Input<int>? SoftDeleteRetentionDays { get; set; }

        /// <summary>
        /// The GUID of the DuploCloud tenant that the key vault will be created in.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// The URI of the Key Vault, used for performing operations on keys and secrets.
        /// </summary>
        [Input("vaultUri")]
        public Input<string>? VaultUri { get; set; }

        public AzureTenantKeyVaultState()
        {
        }
        public static new AzureTenantKeyVaultState Empty => new AzureTenantKeyVaultState();
    }
}
