// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    /// <summary>
    /// `duplocloud.AzureStorageclassQueue` manages an Azure storage class queue in Duplo.
    /// </summary>
    [PulumiResourceType("duplocloud:index/azureStorageclassQueue:AzureStorageclassQueue")]
    public partial class AzureStorageclassQueue : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the Queue. Changing this forces a new resource to be created.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Specifies the storage class in which to create the queue. Changing this forces a new resource to be created.
        /// </summary>
        [Output("storageAccountName")]
        public Output<string> StorageAccountName { get; private set; } = null!;

        /// <summary>
        /// The GUID of the tenant that the azure storage class queue will be created in.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        /// <summary>
        /// The URL of the Queue.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a AzureStorageclassQueue resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AzureStorageclassQueue(string name, AzureStorageclassQueueArgs args, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureStorageclassQueue:AzureStorageclassQueue", name, args ?? new AzureStorageclassQueueArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AzureStorageclassQueue(string name, Input<string> id, AzureStorageclassQueueState? state = null, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureStorageclassQueue:AzureStorageclassQueue", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/duplocloud/pulumi-duplocloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AzureStorageclassQueue resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AzureStorageclassQueue Get(string name, Input<string> id, AzureStorageclassQueueState? state = null, CustomResourceOptions? options = null)
        {
            return new AzureStorageclassQueue(name, id, state, options);
        }
    }

    public sealed class AzureStorageclassQueueArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Queue. Changing this forces a new resource to be created.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Specifies the storage class in which to create the queue. Changing this forces a new resource to be created.
        /// </summary>
        [Input("storageAccountName", required: true)]
        public Input<string> StorageAccountName { get; set; } = null!;

        /// <summary>
        /// The GUID of the tenant that the azure storage class queue will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public AzureStorageclassQueueArgs()
        {
        }
        public static new AzureStorageclassQueueArgs Empty => new AzureStorageclassQueueArgs();
    }

    public sealed class AzureStorageclassQueueState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the Queue. Changing this forces a new resource to be created.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Specifies the storage class in which to create the queue. Changing this forces a new resource to be created.
        /// </summary>
        [Input("storageAccountName")]
        public Input<string>? StorageAccountName { get; set; }

        /// <summary>
        /// The GUID of the tenant that the azure storage class queue will be created in.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// The URL of the Queue.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public AzureStorageclassQueueState()
        {
        }
        public static new AzureStorageclassQueueState Empty => new AzureStorageclassQueueState();
    }
}
