// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud
{
    /// <summary>
    /// `duplocloud.AzureTenantKeyVaultSecret` manages a azure Key Vault secret in DuploCloud.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Duplocloud = Pulumi.Duplocloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var tenant = new Duplocloud.Tenant("tenant", new()
    ///     {
    ///         AccountName = "test",
    ///         PlanId = "test",
    ///     });
    /// 
    ///     var kv = new Duplocloud.AzureTenantKeyVault("kv", new()
    ///     {
    ///         TenantId = tenant.TenantId,
    ///         Name = "tst-kv001",
    ///         SkuName = "standard",
    ///         PurgeProtectionEnabled = true,
    ///         SoftDeleteRetentionDays = 90,
    ///     });
    /// 
    ///     var kvSecret = new Duplocloud.AzureTenantKeyVaultSecret("kv_secret", new()
    ///     {
    ///         TenantId = tenant.TenantId,
    ///         VaultName = kv.Name,
    ///         Name = "Sec001",
    ///         Value = "SecVal001",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Example: Importing an existing Azure Key Vault Secret
    /// 
    ///  - *TENANT_ID* is the tenant GUID
    /// 
    ///  - *VAULT_NAME* is the name of the Azure Key Vault
    /// 
    ///  - *SECRET_NAME* is the name of the Azure Key Vault Secret
    /// 
    /// ```sh
    /// $ pulumi import duplocloud:index/azureTenantKeyVaultSecret:AzureTenantKeyVaultSecret kv_secret *TENANT_ID*/*VAULT_NAME*/*SECRET_NAME*
    /// ```
    /// </summary>
    [DuplocloudResourceType("duplocloud:index/azureTenantKeyVaultSecret:AzureTenantKeyVaultSecret")]
    public partial class AzureTenantKeyVaultSecret : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The azure ID of the Key Vault secret.
        /// </summary>
        [Output("azureId")]
        public Output<string> AzureId { get; private set; } = null!;

        /// <summary>
        /// Specifies the content type for the Key Vault Secret.
        /// </summary>
        [Output("contentType")]
        public Output<string> ContentType { get; private set; } = null!;

        /// <summary>
        /// Specifies the name of the Key Vault Secret.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Reflects the deletion recovery level currently in effect for secrets in the current vault.
        /// </summary>
        [Output("recoveryLevel")]
        public Output<string> RecoveryLevel { get; private set; } = null!;

        /// <summary>
        /// The GUID of the DuploCloud tenant that the key vault secret will be created in.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        /// <summary>
        /// Specifies the value of the Key Vault Secret. Changing this will create a new version of the Key Vault Secret.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;

        /// <summary>
        /// Base URL of the Azure Key Vault
        /// </summary>
        [Output("vaultBaseUrl")]
        public Output<string> VaultBaseUrl { get; private set; } = null!;

        /// <summary>
        /// Name of the Key Vault where the Secret should be created.
        /// </summary>
        [Output("vaultName")]
        public Output<string> VaultName { get; private set; } = null!;

        /// <summary>
        /// The current version of the Key Vault Secret.
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a AzureTenantKeyVaultSecret resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AzureTenantKeyVaultSecret(string name, AzureTenantKeyVaultSecretArgs args, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureTenantKeyVaultSecret:AzureTenantKeyVaultSecret", name, args ?? new AzureTenantKeyVaultSecretArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AzureTenantKeyVaultSecret(string name, Input<string> id, AzureTenantKeyVaultSecretState? state = null, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureTenantKeyVaultSecret:AzureTenantKeyVaultSecret", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/duplocloud/pulumi-duplocloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AzureTenantKeyVaultSecret resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AzureTenantKeyVaultSecret Get(string name, Input<string> id, AzureTenantKeyVaultSecretState? state = null, CustomResourceOptions? options = null)
        {
            return new AzureTenantKeyVaultSecret(name, id, state, options);
        }
    }

    public sealed class AzureTenantKeyVaultSecretArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the content type for the Key Vault Secret.
        /// </summary>
        [Input("contentType")]
        public Input<string>? ContentType { get; set; }

        /// <summary>
        /// Specifies the name of the Key Vault Secret.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The GUID of the DuploCloud tenant that the key vault secret will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        /// <summary>
        /// Specifies the value of the Key Vault Secret. Changing this will create a new version of the Key Vault Secret.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        /// <summary>
        /// Name of the Key Vault where the Secret should be created.
        /// </summary>
        [Input("vaultName", required: true)]
        public Input<string> VaultName { get; set; } = null!;

        public AzureTenantKeyVaultSecretArgs()
        {
        }
        public static new AzureTenantKeyVaultSecretArgs Empty => new AzureTenantKeyVaultSecretArgs();
    }

    public sealed class AzureTenantKeyVaultSecretState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The azure ID of the Key Vault secret.
        /// </summary>
        [Input("azureId")]
        public Input<string>? AzureId { get; set; }

        /// <summary>
        /// Specifies the content type for the Key Vault Secret.
        /// </summary>
        [Input("contentType")]
        public Input<string>? ContentType { get; set; }

        /// <summary>
        /// Specifies the name of the Key Vault Secret.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reflects the deletion recovery level currently in effect for secrets in the current vault.
        /// </summary>
        [Input("recoveryLevel")]
        public Input<string>? RecoveryLevel { get; set; }

        /// <summary>
        /// The GUID of the DuploCloud tenant that the key vault secret will be created in.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// Specifies the value of the Key Vault Secret. Changing this will create a new version of the Key Vault Secret.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        /// <summary>
        /// Base URL of the Azure Key Vault
        /// </summary>
        [Input("vaultBaseUrl")]
        public Input<string>? VaultBaseUrl { get; set; }

        /// <summary>
        /// Name of the Key Vault where the Secret should be created.
        /// </summary>
        [Input("vaultName")]
        public Input<string>? VaultName { get; set; }

        /// <summary>
        /// The current version of the Key Vault Secret.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public AzureTenantKeyVaultSecretState()
        {
        }
        public static new AzureTenantKeyVaultSecretState Empty => new AzureTenantKeyVaultSecretState();
    }
}
