// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud
{
    /// <summary>
    /// `duplocloud.AzureAvailabilitySet` manages logical groupings of VMs that enhance reliability by placing VMs in different fault domains to minimize correlated failures, offering improved VM-to-VM latency and high availability, with no extra cost beyond the VM instances themselves, though they may still be affected by shared infrastructure failures.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Duplocloud = Pulumi.Duplocloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var myapp = new Duplocloud.Tenant("myapp", new()
    ///     {
    ///         AccountName = "myapp",
    ///         PlanId = "default",
    ///     });
    /// 
    ///     var st = new Duplocloud.AzureAvailabilitySet("st", new()
    ///     {
    ///         TenantId = myapp.TenantId,
    ///         Name = "availset",
    ///         UseManagedDisk = "Aligned",
    ///         PlatformUpdateDomainCount = 5,
    ///         PlatformFaultDomainCount = 2,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Example: Importing an existing Azure Availablitu set
    /// 
    ///  - *TENANT_ID* is the tenant GUID
    /// 
    ///  - *NAME* is the  name of the Azure Availability set
    /// 
    /// # 
    /// 
    /// ```sh
    /// $ pulumi import duplocloud:index/azureAvailabilitySet:AzureAvailabilitySet this *TENANT_ID*/availability-set/*NAME*
    /// ```
    /// </summary>
    [DuplocloudResourceType("duplocloud:index/azureAvailabilitySet:AzureAvailabilitySet")]
    public partial class AzureAvailabilitySet : global::Pulumi.CustomResource
    {
        [Output("availabilitySetId")]
        public Output<string> AvailabilitySetId { get; private set; } = null!;

        [Output("location")]
        public Output<string> Location { get; private set; } = null!;

        /// <summary>
        /// The name for availability set
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Specify platform fault domain count betweem 1-3, for availability set. Virtual machines in the same fault domain share a common power source and physical network switch. Defaults to `2`.
        /// </summary>
        [Output("platformFaultDomainCount")]
        public Output<int?> PlatformFaultDomainCount { get; private set; } = null!;

        /// <summary>
        /// Specify platform update domain count between 1-20, for availability set. Virtual machines in the same update domain will be restarted together during planned maintenance. Azure never restarts more than one update domain at a time. Defaults to `5`.
        /// </summary>
        [Output("platformUpdateDomainCount")]
        public Output<int?> PlatformUpdateDomainCount { get; private set; } = null!;

        [Output("tags")]
        public Output<ImmutableDictionary<string, string>> Tags { get; private set; } = null!;

        /// <summary>
        /// The GUID of the tenant that the host will be created in.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Set this to `Aligned` if you plan to create virtual machines in this availability set with managed disks. Defaults to `Classic`.
        /// </summary>
        [Output("useManagedDisk")]
        public Output<string?> UseManagedDisk { get; private set; } = null!;

        [Output("virtualMachines")]
        public Output<ImmutableArray<Outputs.AzureAvailabilitySetVirtualMachine>> VirtualMachines { get; private set; } = null!;


        /// <summary>
        /// Create a AzureAvailabilitySet resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AzureAvailabilitySet(string name, AzureAvailabilitySetArgs args, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureAvailabilitySet:AzureAvailabilitySet", name, args ?? new AzureAvailabilitySetArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AzureAvailabilitySet(string name, Input<string> id, AzureAvailabilitySetState? state = null, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureAvailabilitySet:AzureAvailabilitySet", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/duplocloud/pulumi-duplocloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AzureAvailabilitySet resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AzureAvailabilitySet Get(string name, Input<string> id, AzureAvailabilitySetState? state = null, CustomResourceOptions? options = null)
        {
            return new AzureAvailabilitySet(name, id, state, options);
        }
    }

    public sealed class AzureAvailabilitySetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name for availability set
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Specify platform fault domain count betweem 1-3, for availability set. Virtual machines in the same fault domain share a common power source and physical network switch. Defaults to `2`.
        /// </summary>
        [Input("platformFaultDomainCount")]
        public Input<int>? PlatformFaultDomainCount { get; set; }

        /// <summary>
        /// Specify platform update domain count between 1-20, for availability set. Virtual machines in the same update domain will be restarted together during planned maintenance. Azure never restarts more than one update domain at a time. Defaults to `5`.
        /// </summary>
        [Input("platformUpdateDomainCount")]
        public Input<int>? PlatformUpdateDomainCount { get; set; }

        /// <summary>
        /// The GUID of the tenant that the host will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        /// <summary>
        /// Set this to `Aligned` if you plan to create virtual machines in this availability set with managed disks. Defaults to `Classic`.
        /// </summary>
        [Input("useManagedDisk")]
        public Input<string>? UseManagedDisk { get; set; }

        public AzureAvailabilitySetArgs()
        {
        }
        public static new AzureAvailabilitySetArgs Empty => new AzureAvailabilitySetArgs();
    }

    public sealed class AzureAvailabilitySetState : global::Pulumi.ResourceArgs
    {
        [Input("availabilitySetId")]
        public Input<string>? AvailabilitySetId { get; set; }

        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// The name for availability set
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Specify platform fault domain count betweem 1-3, for availability set. Virtual machines in the same fault domain share a common power source and physical network switch. Defaults to `2`.
        /// </summary>
        [Input("platformFaultDomainCount")]
        public Input<int>? PlatformFaultDomainCount { get; set; }

        /// <summary>
        /// Specify platform update domain count between 1-20, for availability set. Virtual machines in the same update domain will be restarted together during planned maintenance. Azure never restarts more than one update domain at a time. Defaults to `5`.
        /// </summary>
        [Input("platformUpdateDomainCount")]
        public Input<int>? PlatformUpdateDomainCount { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The GUID of the tenant that the host will be created in.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Set this to `Aligned` if you plan to create virtual machines in this availability set with managed disks. Defaults to `Classic`.
        /// </summary>
        [Input("useManagedDisk")]
        public Input<string>? UseManagedDisk { get; set; }

        [Input("virtualMachines")]
        private InputList<Inputs.AzureAvailabilitySetVirtualMachineGetArgs>? _virtualMachines;
        public InputList<Inputs.AzureAvailabilitySetVirtualMachineGetArgs> VirtualMachines
        {
            get => _virtualMachines ?? (_virtualMachines = new InputList<Inputs.AzureAvailabilitySetVirtualMachineGetArgs>());
            set => _virtualMachines = value;
        }

        public AzureAvailabilitySetState()
        {
        }
        public static new AzureAvailabilitySetState Empty => new AzureAvailabilitySetState();
    }
}
