// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    /// <summary>
    /// `duplocloud.AzureCosmosDbAccount` manages cosmos db account resource for azure
    /// 
    /// ## Import
    /// 
    /// Example: Importing an existing Azure CosmosDB Account
    /// 
    ///  - *TENANT_ID* is the tenant GUID
    /// 
    ///  - *NAME* is the name of the Azure Cosmosdb Account
    /// 
    /// # 
    /// 
    /// ```sh
    /// $ pulumi import duplocloud:index/azureCosmosDbAccount:AzureCosmosDbAccount account *TENANT_ID*/cosmosdb/account/*NAME*
    /// ```
    /// </summary>
    [PulumiResourceType("duplocloud:index/azureCosmosDbAccount:AzureCosmosDbAccount")]
    public partial class AzureCosmosDbAccount : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Backup policy for cosmos db account.
        /// 		&gt; ⚠️ **Note:**:
        /// 		&gt; You can only configure backup*interval, backup*retention*interval and backup*storage*redundancy when the type field is set to periodic
        /// </summary>
        [Output("backupPolicy")]
        public Output<Outputs.AzureCosmosDbAccountBackupPolicy> BackupPolicy { get; private set; } = null!;

        /// <summary>
        /// Name of the Cosmos DB capability
        /// </summary>
        [Output("capabilities")]
        public Output<ImmutableArray<Outputs.AzureCosmosDbAccountCapability>> Capabilities { get; private set; } = null!;

        [Output("capacityMode")]
        public Output<string> CapacityMode { get; private set; } = null!;

        /// <summary>
        /// Specify the consistency policy for the Cosmos DB account.
        /// </summary>
        [Output("consistencyPolicy")]
        public Output<Outputs.AzureCosmosDbAccountConsistencyPolicy> ConsistencyPolicy { get; private set; } = null!;

        /// <summary>
        /// Disable write operations on metadata resources (databases, containers, throughput) via account keys Defaults to `false`.
        /// </summary>
        [Output("disableKeyBasedMetadataWriteAccess")]
        public Output<bool?> DisableKeyBasedMetadataWriteAccess { get; private set; } = null!;

        /// <summary>
        /// Flag to indicate whether Free Tier is enabled. Defaults to `false`.
        /// </summary>
        [Output("enableFreeTier")]
        public Output<bool?> EnableFreeTier { get; private set; } = null!;

        /// <summary>
        /// The endpoint used to connect to the CosmosDB account.
        /// </summary>
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        /// <summary>
        /// Specifies a geo*location resource, used to define where data should be replicated with the failover*priority 0 specifying the primary location
        /// </summary>
        [Output("geoLocations")]
        public Output<ImmutableArray<Outputs.AzureCosmosDbAccountGeoLocation>> GeoLocations { get; private set; } = null!;

        /// <summary>
        /// Enables virtual network filtering for this Cosmos DB account.
        /// </summary>
        [Output("isVirtualNetworkFilterEnabled")]
        public Output<bool> IsVirtualNetworkFilterEnabled { get; private set; } = null!;

        /// <summary>
        /// Indicates the type of database account. This can only be set at database account creation.
        /// 		Allowed Account Kind : GlobalDocumentDB.
        /// 		Future support MongoDB, Parse
        /// </summary>
        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        /// <summary>
        /// An array that contains the georeplication locations enabled for the Cosmos DB account.
        /// </summary>
        [Output("locations")]
        public Output<string> Locations { get; private set; } = null!;

        /// <summary>
        /// The name for availability set
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The primary key for the CosmosDB account.
        /// </summary>
        [Output("primaryMasterKey")]
        public Output<string> PrimaryMasterKey { get; private set; } = null!;

        /// <summary>
        /// The primary MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Output("primaryMongoConnectionString")]
        public Output<string> PrimaryMongoConnectionString { get; private set; } = null!;

        /// <summary>
        /// The primary readonly key for the CosmosDB account.
        /// </summary>
        [Output("primaryReadonlyMasterKey")]
        public Output<string> PrimaryReadonlyMasterKey { get; private set; } = null!;

        /// <summary>
        /// The primary readonly MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Output("primaryReadonlyMongoConnectionString")]
        public Output<string> PrimaryReadonlyMongoConnectionString { get; private set; } = null!;

        /// <summary>
        /// The primary readonly SQL connection string for the CosmosDB account.
        /// </summary>
        [Output("primaryReadonlySqlConnectionString")]
        public Output<string> PrimaryReadonlySqlConnectionString { get; private set; } = null!;

        /// <summary>
        /// The primary SQL connection string for the CosmosDB account.
        /// </summary>
        [Output("primarySqlConnectionString")]
        public Output<string> PrimarySqlConnectionString { get; private set; } = null!;

        /// <summary>
        /// Flag to indicate whether to enable/disable public network access. Defaults to `Enabled`.
        /// </summary>
        [Output("publicNetworkAccess")]
        public Output<string?> PublicNetworkAccess { get; private set; } = null!;

        /// <summary>
        /// The list of read endpoints for the CosmosDB account.
        /// </summary>
        [Output("readEndpoints")]
        public Output<ImmutableArray<string>> ReadEndpoints { get; private set; } = null!;

        /// <summary>
        /// The secondary key for the CosmosDB account.
        /// </summary>
        [Output("secondaryMasterKey")]
        public Output<string> SecondaryMasterKey { get; private set; } = null!;

        /// <summary>
        /// The secondary MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Output("secondaryMongoConnectionString")]
        public Output<string> SecondaryMongoConnectionString { get; private set; } = null!;

        /// <summary>
        /// The secondary readonly key for the CosmosDB account.
        /// </summary>
        [Output("secondaryReadonlyMasterKey")]
        public Output<string> SecondaryReadonlyMasterKey { get; private set; } = null!;

        /// <summary>
        /// The secondary readonly MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Output("secondaryReadonlyMongoConnectionString")]
        public Output<string> SecondaryReadonlyMongoConnectionString { get; private set; } = null!;

        /// <summary>
        /// The secondary readonly SQL connection string for the CosmosDB account.
        /// </summary>
        [Output("secondaryReadonlySqlConnectionString")]
        public Output<string> SecondaryReadonlySqlConnectionString { get; private set; } = null!;

        /// <summary>
        /// The secondary SQL connection string for the CosmosDB account.
        /// </summary>
        [Output("secondarySqlConnectionString")]
        public Output<string> SecondarySqlConnectionString { get; private set; } = null!;

        /// <summary>
        /// The GUID of the tenant that the host will be created in.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;

        /// <summary>
        /// Specifies the  Cosmos DB account type. Defaults to `Microsoft.DocumentDB/databaseAccounts`.
        /// </summary>
        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;

        /// <summary>
        /// A list of virtual network rules for the Cosmos DB account. This is used to define which subnets are allowed to access this CosmosDB account
        /// </summary>
        [Output("virtualNetworkRules")]
        public Output<ImmutableArray<Outputs.AzureCosmosDbAccountVirtualNetworkRule>> VirtualNetworkRules { get; private set; } = null!;

        /// <summary>
        /// The list of write endpoints for the CosmosDB account.
        /// </summary>
        [Output("writeEndpoints")]
        public Output<ImmutableArray<string>> WriteEndpoints { get; private set; } = null!;


        /// <summary>
        /// Create a AzureCosmosDbAccount resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AzureCosmosDbAccount(string name, AzureCosmosDbAccountArgs args, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureCosmosDbAccount:AzureCosmosDbAccount", name, args ?? new AzureCosmosDbAccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AzureCosmosDbAccount(string name, Input<string> id, AzureCosmosDbAccountState? state = null, CustomResourceOptions? options = null)
            : base("duplocloud:index/azureCosmosDbAccount:AzureCosmosDbAccount", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/duplocloud/pulumi-duplocloud",
                AdditionalSecretOutputs =
                {
                    "primaryMasterKey",
                    "primaryReadonlyMasterKey",
                    "secondaryMasterKey",
                    "secondaryReadonlyMasterKey",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AzureCosmosDbAccount resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AzureCosmosDbAccount Get(string name, Input<string> id, AzureCosmosDbAccountState? state = null, CustomResourceOptions? options = null)
        {
            return new AzureCosmosDbAccount(name, id, state, options);
        }
    }

    public sealed class AzureCosmosDbAccountArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Backup policy for cosmos db account.
        /// 		&gt; ⚠️ **Note:**:
        /// 		&gt; You can only configure backup*interval, backup*retention*interval and backup*storage*redundancy when the type field is set to periodic
        /// </summary>
        [Input("backupPolicy")]
        public Input<Inputs.AzureCosmosDbAccountBackupPolicyArgs>? BackupPolicy { get; set; }

        [Input("capabilities")]
        private InputList<Inputs.AzureCosmosDbAccountCapabilityArgs>? _capabilities;

        /// <summary>
        /// Name of the Cosmos DB capability
        /// </summary>
        public InputList<Inputs.AzureCosmosDbAccountCapabilityArgs> Capabilities
        {
            get => _capabilities ?? (_capabilities = new InputList<Inputs.AzureCosmosDbAccountCapabilityArgs>());
            set => _capabilities = value;
        }

        /// <summary>
        /// Specify the consistency policy for the Cosmos DB account.
        /// </summary>
        [Input("consistencyPolicy")]
        public Input<Inputs.AzureCosmosDbAccountConsistencyPolicyArgs>? ConsistencyPolicy { get; set; }

        /// <summary>
        /// Disable write operations on metadata resources (databases, containers, throughput) via account keys Defaults to `false`.
        /// </summary>
        [Input("disableKeyBasedMetadataWriteAccess")]
        public Input<bool>? DisableKeyBasedMetadataWriteAccess { get; set; }

        /// <summary>
        /// Flag to indicate whether Free Tier is enabled. Defaults to `false`.
        /// </summary>
        [Input("enableFreeTier")]
        public Input<bool>? EnableFreeTier { get; set; }

        [Input("geoLocations", required: true)]
        private InputList<Inputs.AzureCosmosDbAccountGeoLocationArgs>? _geoLocations;

        /// <summary>
        /// Specifies a geo*location resource, used to define where data should be replicated with the failover*priority 0 specifying the primary location
        /// </summary>
        public InputList<Inputs.AzureCosmosDbAccountGeoLocationArgs> GeoLocations
        {
            get => _geoLocations ?? (_geoLocations = new InputList<Inputs.AzureCosmosDbAccountGeoLocationArgs>());
            set => _geoLocations = value;
        }

        /// <summary>
        /// Enables virtual network filtering for this Cosmos DB account.
        /// </summary>
        [Input("isVirtualNetworkFilterEnabled")]
        public Input<bool>? IsVirtualNetworkFilterEnabled { get; set; }

        /// <summary>
        /// Indicates the type of database account. This can only be set at database account creation.
        /// 		Allowed Account Kind : GlobalDocumentDB.
        /// 		Future support MongoDB, Parse
        /// </summary>
        [Input("kind", required: true)]
        public Input<string> Kind { get; set; } = null!;

        /// <summary>
        /// The name for availability set
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Flag to indicate whether to enable/disable public network access. Defaults to `Enabled`.
        /// </summary>
        [Input("publicNetworkAccess")]
        public Input<string>? PublicNetworkAccess { get; set; }

        /// <summary>
        /// The GUID of the tenant that the host will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        /// <summary>
        /// Specifies the  Cosmos DB account type. Defaults to `Microsoft.DocumentDB/databaseAccounts`.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("virtualNetworkRules")]
        private InputList<Inputs.AzureCosmosDbAccountVirtualNetworkRuleArgs>? _virtualNetworkRules;

        /// <summary>
        /// A list of virtual network rules for the Cosmos DB account. This is used to define which subnets are allowed to access this CosmosDB account
        /// </summary>
        public InputList<Inputs.AzureCosmosDbAccountVirtualNetworkRuleArgs> VirtualNetworkRules
        {
            get => _virtualNetworkRules ?? (_virtualNetworkRules = new InputList<Inputs.AzureCosmosDbAccountVirtualNetworkRuleArgs>());
            set => _virtualNetworkRules = value;
        }

        public AzureCosmosDbAccountArgs()
        {
        }
        public static new AzureCosmosDbAccountArgs Empty => new AzureCosmosDbAccountArgs();
    }

    public sealed class AzureCosmosDbAccountState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Backup policy for cosmos db account.
        /// 		&gt; ⚠️ **Note:**:
        /// 		&gt; You can only configure backup*interval, backup*retention*interval and backup*storage*redundancy when the type field is set to periodic
        /// </summary>
        [Input("backupPolicy")]
        public Input<Inputs.AzureCosmosDbAccountBackupPolicyGetArgs>? BackupPolicy { get; set; }

        [Input("capabilities")]
        private InputList<Inputs.AzureCosmosDbAccountCapabilityGetArgs>? _capabilities;

        /// <summary>
        /// Name of the Cosmos DB capability
        /// </summary>
        public InputList<Inputs.AzureCosmosDbAccountCapabilityGetArgs> Capabilities
        {
            get => _capabilities ?? (_capabilities = new InputList<Inputs.AzureCosmosDbAccountCapabilityGetArgs>());
            set => _capabilities = value;
        }

        [Input("capacityMode")]
        public Input<string>? CapacityMode { get; set; }

        /// <summary>
        /// Specify the consistency policy for the Cosmos DB account.
        /// </summary>
        [Input("consistencyPolicy")]
        public Input<Inputs.AzureCosmosDbAccountConsistencyPolicyGetArgs>? ConsistencyPolicy { get; set; }

        /// <summary>
        /// Disable write operations on metadata resources (databases, containers, throughput) via account keys Defaults to `false`.
        /// </summary>
        [Input("disableKeyBasedMetadataWriteAccess")]
        public Input<bool>? DisableKeyBasedMetadataWriteAccess { get; set; }

        /// <summary>
        /// Flag to indicate whether Free Tier is enabled. Defaults to `false`.
        /// </summary>
        [Input("enableFreeTier")]
        public Input<bool>? EnableFreeTier { get; set; }

        /// <summary>
        /// The endpoint used to connect to the CosmosDB account.
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        [Input("geoLocations")]
        private InputList<Inputs.AzureCosmosDbAccountGeoLocationGetArgs>? _geoLocations;

        /// <summary>
        /// Specifies a geo*location resource, used to define where data should be replicated with the failover*priority 0 specifying the primary location
        /// </summary>
        public InputList<Inputs.AzureCosmosDbAccountGeoLocationGetArgs> GeoLocations
        {
            get => _geoLocations ?? (_geoLocations = new InputList<Inputs.AzureCosmosDbAccountGeoLocationGetArgs>());
            set => _geoLocations = value;
        }

        /// <summary>
        /// Enables virtual network filtering for this Cosmos DB account.
        /// </summary>
        [Input("isVirtualNetworkFilterEnabled")]
        public Input<bool>? IsVirtualNetworkFilterEnabled { get; set; }

        /// <summary>
        /// Indicates the type of database account. This can only be set at database account creation.
        /// 		Allowed Account Kind : GlobalDocumentDB.
        /// 		Future support MongoDB, Parse
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// An array that contains the georeplication locations enabled for the Cosmos DB account.
        /// </summary>
        [Input("locations")]
        public Input<string>? Locations { get; set; }

        /// <summary>
        /// The name for availability set
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("primaryMasterKey")]
        private Input<string>? _primaryMasterKey;

        /// <summary>
        /// The primary key for the CosmosDB account.
        /// </summary>
        public Input<string>? PrimaryMasterKey
        {
            get => _primaryMasterKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _primaryMasterKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The primary MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Input("primaryMongoConnectionString")]
        public Input<string>? PrimaryMongoConnectionString { get; set; }

        [Input("primaryReadonlyMasterKey")]
        private Input<string>? _primaryReadonlyMasterKey;

        /// <summary>
        /// The primary readonly key for the CosmosDB account.
        /// </summary>
        public Input<string>? PrimaryReadonlyMasterKey
        {
            get => _primaryReadonlyMasterKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _primaryReadonlyMasterKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The primary readonly MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Input("primaryReadonlyMongoConnectionString")]
        public Input<string>? PrimaryReadonlyMongoConnectionString { get; set; }

        /// <summary>
        /// The primary readonly SQL connection string for the CosmosDB account.
        /// </summary>
        [Input("primaryReadonlySqlConnectionString")]
        public Input<string>? PrimaryReadonlySqlConnectionString { get; set; }

        /// <summary>
        /// The primary SQL connection string for the CosmosDB account.
        /// </summary>
        [Input("primarySqlConnectionString")]
        public Input<string>? PrimarySqlConnectionString { get; set; }

        /// <summary>
        /// Flag to indicate whether to enable/disable public network access. Defaults to `Enabled`.
        /// </summary>
        [Input("publicNetworkAccess")]
        public Input<string>? PublicNetworkAccess { get; set; }

        [Input("readEndpoints")]
        private InputList<string>? _readEndpoints;

        /// <summary>
        /// The list of read endpoints for the CosmosDB account.
        /// </summary>
        public InputList<string> ReadEndpoints
        {
            get => _readEndpoints ?? (_readEndpoints = new InputList<string>());
            set => _readEndpoints = value;
        }

        [Input("secondaryMasterKey")]
        private Input<string>? _secondaryMasterKey;

        /// <summary>
        /// The secondary key for the CosmosDB account.
        /// </summary>
        public Input<string>? SecondaryMasterKey
        {
            get => _secondaryMasterKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secondaryMasterKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The secondary MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Input("secondaryMongoConnectionString")]
        public Input<string>? SecondaryMongoConnectionString { get; set; }

        [Input("secondaryReadonlyMasterKey")]
        private Input<string>? _secondaryReadonlyMasterKey;

        /// <summary>
        /// The secondary readonly key for the CosmosDB account.
        /// </summary>
        public Input<string>? SecondaryReadonlyMasterKey
        {
            get => _secondaryReadonlyMasterKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secondaryReadonlyMasterKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The secondary readonly MongoDB connection string for the CosmosDB account.
        /// </summary>
        [Input("secondaryReadonlyMongoConnectionString")]
        public Input<string>? SecondaryReadonlyMongoConnectionString { get; set; }

        /// <summary>
        /// The secondary readonly SQL connection string for the CosmosDB account.
        /// </summary>
        [Input("secondaryReadonlySqlConnectionString")]
        public Input<string>? SecondaryReadonlySqlConnectionString { get; set; }

        /// <summary>
        /// The secondary SQL connection string for the CosmosDB account.
        /// </summary>
        [Input("secondarySqlConnectionString")]
        public Input<string>? SecondarySqlConnectionString { get; set; }

        /// <summary>
        /// The GUID of the tenant that the host will be created in.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        /// <summary>
        /// Specifies the  Cosmos DB account type. Defaults to `Microsoft.DocumentDB/databaseAccounts`.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("virtualNetworkRules")]
        private InputList<Inputs.AzureCosmosDbAccountVirtualNetworkRuleGetArgs>? _virtualNetworkRules;

        /// <summary>
        /// A list of virtual network rules for the Cosmos DB account. This is used to define which subnets are allowed to access this CosmosDB account
        /// </summary>
        public InputList<Inputs.AzureCosmosDbAccountVirtualNetworkRuleGetArgs> VirtualNetworkRules
        {
            get => _virtualNetworkRules ?? (_virtualNetworkRules = new InputList<Inputs.AzureCosmosDbAccountVirtualNetworkRuleGetArgs>());
            set => _virtualNetworkRules = value;
        }

        [Input("writeEndpoints")]
        private InputList<string>? _writeEndpoints;

        /// <summary>
        /// The list of write endpoints for the CosmosDB account.
        /// </summary>
        public InputList<string> WriteEndpoints
        {
            get => _writeEndpoints ?? (_writeEndpoints = new InputList<string>());
            set => _writeEndpoints = value;
        }

        public AzureCosmosDbAccountState()
        {
        }
        public static new AzureCosmosDbAccountState Empty => new AzureCosmosDbAccountState();
    }
}
