// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud
{
    public static class GetAzureStorageAccountKey
    {
        /// <summary>
        /// `duplocloud.getAzureStorageAccountKey` retrieves a azure storage account key in Duplo.
        /// </summary>
        public static Task<GetAzureStorageAccountKeyResult> InvokeAsync(GetAzureStorageAccountKeyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAzureStorageAccountKeyResult>("duplocloud:index/getAzureStorageAccountKey:getAzureStorageAccountKey", args ?? new GetAzureStorageAccountKeyArgs(), options.WithDefaults());

        /// <summary>
        /// `duplocloud.getAzureStorageAccountKey` retrieves a azure storage account key in Duplo.
        /// </summary>
        public static Output<GetAzureStorageAccountKeyResult> Invoke(GetAzureStorageAccountKeyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAzureStorageAccountKeyResult>("duplocloud:index/getAzureStorageAccountKey:getAzureStorageAccountKey", args ?? new GetAzureStorageAccountKeyInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// `duplocloud.getAzureStorageAccountKey` retrieves a azure storage account key in Duplo.
        /// </summary>
        public static Output<GetAzureStorageAccountKeyResult> Invoke(GetAzureStorageAccountKeyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAzureStorageAccountKeyResult>("duplocloud:index/getAzureStorageAccountKey:getAzureStorageAccountKey", args ?? new GetAzureStorageAccountKeyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAzureStorageAccountKeyArgs : global::Pulumi.InvokeArgs
    {
        [Input("storageAccountName", required: true)]
        public string StorageAccountName { get; set; } = null!;

        [Input("tenantId", required: true)]
        public string TenantId { get; set; } = null!;

        public GetAzureStorageAccountKeyArgs()
        {
        }
        public static new GetAzureStorageAccountKeyArgs Empty => new GetAzureStorageAccountKeyArgs();
    }

    public sealed class GetAzureStorageAccountKeyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("storageAccountName", required: true)]
        public Input<string> StorageAccountName { get; set; } = null!;

        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public GetAzureStorageAccountKeyInvokeArgs()
        {
        }
        public static new GetAzureStorageAccountKeyInvokeArgs Empty => new GetAzureStorageAccountKeyInvokeArgs();
    }


    [OutputType]
    public sealed class GetAzureStorageAccountKeyResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string KeyName;
        public readonly string KeyValue;
        public readonly string StorageAccountName;
        public readonly string TenantId;

        [OutputConstructor]
        private GetAzureStorageAccountKeyResult(
            string id,

            string keyName,

            string keyValue,

            string storageAccountName,

            string tenantId)
        {
            Id = id;
            KeyName = keyName;
            KeyValue = keyValue;
            StorageAccountName = storageAccountName;
            TenantId = tenantId;
        }
    }
}
