// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    public static class GetK8sJob
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var job = Pulumi.GetK8sJob.Invoke(new()
        ///     {
        ///         TenantId = tenantId,
        ///         Metadata = new Pulumi.Inputs.GetK8sJobMetadataInputArgs
        ///         {
        ///             Name = "datajob",
        ///         },
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["metadata"] = job.Apply(getK8sJobResult =&gt; getK8sJobResult.Metadata?.Namespace),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetK8sJobResult> InvokeAsync(GetK8sJobArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetK8sJobResult>("duplocloud:index/getK8sJob:getK8sJob", args ?? new GetK8sJobArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var job = Pulumi.GetK8sJob.Invoke(new()
        ///     {
        ///         TenantId = tenantId,
        ///         Metadata = new Pulumi.Inputs.GetK8sJobMetadataInputArgs
        ///         {
        ///             Name = "datajob",
        ///         },
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["metadata"] = job.Apply(getK8sJobResult =&gt; getK8sJobResult.Metadata?.Namespace),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetK8sJobResult> Invoke(GetK8sJobInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetK8sJobResult>("duplocloud:index/getK8sJob:getK8sJob", args ?? new GetK8sJobInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pulumi = Pulumi.Pulumi;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var job = Pulumi.GetK8sJob.Invoke(new()
        ///     {
        ///         TenantId = tenantId,
        ///         Metadata = new Pulumi.Inputs.GetK8sJobMetadataInputArgs
        ///         {
        ///             Name = "datajob",
        ///         },
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["metadata"] = job.Apply(getK8sJobResult =&gt; getK8sJobResult.Metadata?.Namespace),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetK8sJobResult> Invoke(GetK8sJobInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetK8sJobResult>("duplocloud:index/getK8sJob:getK8sJob", args ?? new GetK8sJobInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetK8sJobArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Allocation tags is the simplest way to constraint containers/pods with hosts/nodes. DuploCloud/Kubernetes Orchestrator will make sure containers will run on the hosts having same allocation tags.
        /// </summary>
        [Input("allocationTags")]
        public string? AllocationTags { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("isAnyHostAllowed")]
        public bool? IsAnyHostAllowed { get; set; }

        /// <summary>
        /// Standard job's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
        /// </summary>
        [Input("metadata", required: true)]
        public Inputs.GetK8sJobMetadataArgs Metadata { get; set; } = null!;

        /// <summary>
        /// The GUID of the tenant that the job will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public string TenantId { get; set; } = null!;

        public GetK8sJobArgs()
        {
        }
        public static new GetK8sJobArgs Empty => new GetK8sJobArgs();
    }

    public sealed class GetK8sJobInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Allocation tags is the simplest way to constraint containers/pods with hosts/nodes. DuploCloud/Kubernetes Orchestrator will make sure containers will run on the hosts having same allocation tags.
        /// </summary>
        [Input("allocationTags")]
        public Input<string>? AllocationTags { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("isAnyHostAllowed")]
        public Input<bool>? IsAnyHostAllowed { get; set; }

        /// <summary>
        /// Standard job's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
        /// </summary>
        [Input("metadata", required: true)]
        public Input<Inputs.GetK8sJobMetadataInputArgs> Metadata { get; set; } = null!;

        /// <summary>
        /// The GUID of the tenant that the job will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public GetK8sJobInvokeArgs()
        {
        }
        public static new GetK8sJobInvokeArgs Empty => new GetK8sJobInvokeArgs();
    }


    [OutputType]
    public sealed class GetK8sJobResult
    {
        /// <summary>
        /// Allocation tags is the simplest way to constraint containers/pods with hosts/nodes. DuploCloud/Kubernetes Orchestrator will make sure containers will run on the hosts having same allocation tags.
        /// </summary>
        public readonly string? AllocationTags;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        public readonly bool? IsAnyHostAllowed;
        /// <summary>
        /// Standard job's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
        /// </summary>
        public readonly Outputs.GetK8sJobMetadataResult Metadata;
        /// <summary>
        /// Spec of the job owned by the cluster
        /// </summary>
        public readonly ImmutableArray<Outputs.GetK8sJobSpecResult> Specs;
        /// <summary>
        /// The GUID of the tenant that the job will be created in.
        /// </summary>
        public readonly string TenantId;
        public readonly bool WaitForCompletion;

        [OutputConstructor]
        private GetK8sJobResult(
            string? allocationTags,

            string id,

            bool? isAnyHostAllowed,

            Outputs.GetK8sJobMetadataResult metadata,

            ImmutableArray<Outputs.GetK8sJobSpecResult> specs,

            string tenantId,

            bool waitForCompletion)
        {
            AllocationTags = allocationTags;
            Id = id;
            IsAnyHostAllowed = isAnyHostAllowed;
            Metadata = metadata;
            Specs = specs;
            TenantId = tenantId;
            WaitForCompletion = waitForCompletion;
        }
    }
}
