// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    public static class GetPlanImages
    {
        /// <summary>
        /// `duplocloud.PlanImages` retrieves a list of images for a given plan.
        /// </summary>
        public static Task<GetPlanImagesResult> InvokeAsync(GetPlanImagesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPlanImagesResult>("duplocloud:index/getPlanImages:getPlanImages", args ?? new GetPlanImagesArgs(), options.WithDefaults());

        /// <summary>
        /// `duplocloud.PlanImages` retrieves a list of images for a given plan.
        /// </summary>
        public static Output<GetPlanImagesResult> Invoke(GetPlanImagesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlanImagesResult>("duplocloud:index/getPlanImages:getPlanImages", args ?? new GetPlanImagesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// `duplocloud.PlanImages` retrieves a list of images for a given plan.
        /// </summary>
        public static Output<GetPlanImagesResult> Invoke(GetPlanImagesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlanImagesResult>("duplocloud:index/getPlanImages:getPlanImages", args ?? new GetPlanImagesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPlanImagesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The plan ID
        /// </summary>
        [Input("planId", required: true)]
        public string PlanId { get; set; } = null!;

        public GetPlanImagesArgs()
        {
        }
        public static new GetPlanImagesArgs Empty => new GetPlanImagesArgs();
    }

    public sealed class GetPlanImagesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The plan ID
        /// </summary>
        [Input("planId", required: true)]
        public Input<string> PlanId { get; set; } = null!;

        public GetPlanImagesInvokeArgs()
        {
        }
        public static new GetPlanImagesInvokeArgs Empty => new GetPlanImagesInvokeArgs();
    }


    [OutputType]
    public sealed class GetPlanImagesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of images for this plan.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPlanImagesImageResult> Images;
        /// <summary>
        /// The plan ID
        /// </summary>
        public readonly string PlanId;

        [OutputConstructor]
        private GetPlanImagesResult(
            string id,

            ImmutableArray<Outputs.GetPlanImagesImageResult> images,

            string planId)
        {
            Id = id;
            Images = images;
            PlanId = planId;
        }
    }
}
