// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    public static class GetPlanKmsKey
    {
        /// <summary>
        /// `duplocloud.PlanKms` manages the list of kms avaialble to a plan in Duplo.
        /// 
        /// This resource allows you take control of individual plan kms for a specific plan.
        /// </summary>
        public static Task<GetPlanKmsKeyResult> InvokeAsync(GetPlanKmsKeyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPlanKmsKeyResult>("duplocloud:index/getPlanKmsKey:getPlanKmsKey", args ?? new GetPlanKmsKeyArgs(), options.WithDefaults());

        /// <summary>
        /// `duplocloud.PlanKms` manages the list of kms avaialble to a plan in Duplo.
        /// 
        /// This resource allows you take control of individual plan kms for a specific plan.
        /// </summary>
        public static Output<GetPlanKmsKeyResult> Invoke(GetPlanKmsKeyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlanKmsKeyResult>("duplocloud:index/getPlanKmsKey:getPlanKmsKey", args ?? new GetPlanKmsKeyInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// `duplocloud.PlanKms` manages the list of kms avaialble to a plan in Duplo.
        /// 
        /// This resource allows you take control of individual plan kms for a specific plan.
        /// </summary>
        public static Output<GetPlanKmsKeyResult> Invoke(GetPlanKmsKeyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlanKmsKeyResult>("duplocloud:index/getPlanKmsKey:getPlanKmsKey", args ?? new GetPlanKmsKeyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPlanKmsKeyArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the plan to configure.
        /// </summary>
        [Input("planId", required: true)]
        public string PlanId { get; set; } = null!;

        public GetPlanKmsKeyArgs()
        {
        }
        public static new GetPlanKmsKeyArgs Empty => new GetPlanKmsKeyArgs();
    }

    public sealed class GetPlanKmsKeyInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the plan to configure.
        /// </summary>
        [Input("planId", required: true)]
        public Input<string> PlanId { get; set; } = null!;

        public GetPlanKmsKeyInvokeArgs()
        {
        }
        public static new GetPlanKmsKeyInvokeArgs Empty => new GetPlanKmsKeyInvokeArgs();
    }


    [OutputType]
    public sealed class GetPlanKmsKeyResult
    {
        public readonly ImmutableArray<Outputs.GetPlanKmsKeyDataResult> Datas;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The ID of the plan to configure.
        /// </summary>
        public readonly string PlanId;

        [OutputConstructor]
        private GetPlanKmsKeyResult(
            ImmutableArray<Outputs.GetPlanKmsKeyDataResult> datas,

            string id,

            string planId)
        {
            Datas = datas;
            Id = id;
            PlanId = planId;
        }
    }
}
