// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    public static class GetTenantEksCredentials
    {
        public static Task<GetTenantEksCredentialsResult> InvokeAsync(GetTenantEksCredentialsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTenantEksCredentialsResult>("duplocloud:index/getTenantEksCredentials:getTenantEksCredentials", args ?? new GetTenantEksCredentialsArgs(), options.WithDefaults());

        public static Output<GetTenantEksCredentialsResult> Invoke(GetTenantEksCredentialsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTenantEksCredentialsResult>("duplocloud:index/getTenantEksCredentials:getTenantEksCredentials", args ?? new GetTenantEksCredentialsInvokeArgs(), options.WithDefaults());

        public static Output<GetTenantEksCredentialsResult> Invoke(GetTenantEksCredentialsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTenantEksCredentialsResult>("duplocloud:index/getTenantEksCredentials:getTenantEksCredentials", args ?? new GetTenantEksCredentialsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTenantEksCredentialsArgs : global::Pulumi.InvokeArgs
    {
        [Input("tenantId", required: true)]
        public string TenantId { get; set; } = null!;

        public GetTenantEksCredentialsArgs()
        {
        }
        public static new GetTenantEksCredentialsArgs Empty => new GetTenantEksCredentialsArgs();
    }

    public sealed class GetTenantEksCredentialsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public GetTenantEksCredentialsInvokeArgs()
        {
        }
        public static new GetTenantEksCredentialsInvokeArgs Empty => new GetTenantEksCredentialsInvokeArgs();
    }


    [OutputType]
    public sealed class GetTenantEksCredentialsResult
    {
        public readonly string CaCertificateData;
        public readonly string Endpoint;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string Namespace;
        public readonly string Region;
        public readonly string TenantId;
        public readonly string Token;
        public readonly string Version;

        [OutputConstructor]
        private GetTenantEksCredentialsResult(
            string caCertificateData,

            string endpoint,

            string id,

            string name,

            string @namespace,

            string region,

            string tenantId,

            string token,

            string version)
        {
            CaCertificateData = caCertificateData;
            Endpoint = endpoint;
            Id = id;
            Name = name;
            Namespace = @namespace;
            Region = region;
            TenantId = tenantId;
            Token = token;
            Version = version;
        }
    }
}
