// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi
{
    /// <summary>
    /// `duplocloud.TenantK8sResourceQuota` manages a resource quota of k8s in the tenant.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using System.Text.Json;
    /// using Pulumi;
    /// using Pulumi = DuploCloud.Pulumi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var tenantId = "913a4498-db09-42c0-95b1-88ed26d87b83";
    /// 
    ///     var quota = new Pulumi.TenantK8sResourceQuota("quota", new()
    ///     {
    ///         TenantId = tenantId,
    ///         Name = "kubequota",
    ///         ResourceQuota = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["requests.memory"] = "4Gi",
    ///             ["pods"] = "2",
    ///         }),
    ///         ScopeSelector = JsonSerializer.Serialize(new Dictionary&lt;string, object?&gt;
    ///         {
    ///             ["matchExpressions"] = new[]
    ///             {
    ///                 new Dictionary&lt;string, object?&gt;
    ///                 {
    ///                     ["operator"] = "In",
    ///                     ["scopeName"] = "PriorityClass",
    ///                     ["values"] = new[]
    ///                     {
    ///                         "middle",
    ///                     },
    ///                 },
    ///             },
    ///         }),
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Example: Importing an existing tenant K8s Quota
    /// 
    ///  - *TENANT_ID* is the tenant GUID
    /// 
    ///  - *NAME* is the name given to K8s quota in specified tenant
    /// 
    /// # 
    /// 
    /// ```sh
    /// $ pulumi import duplocloud:index/tenantK8sResourceQuota:TenantK8sResourceQuota quota *TENANT_ID*/k8-quota/*NAME*
    /// ```
    /// </summary>
    [PulumiResourceType("duplocloud:index/tenantK8sResourceQuota:TenantK8sResourceQuota")]
    public partial class TenantK8sResourceQuota : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of the K8's quota.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Limits the total amount of compute, storage, and object resources that a namespace can use to prevent over-consumption and ensure fair resource allocation in a Kubernetes cluster. Should be a JSON-encoded string using jsonencode()
        /// </summary>
        [Output("resourceQuota")]
        public Output<string> ResourceQuota { get; private set; } = null!;

        /// <summary>
        /// Applies quota only to resources matching specified workload scopes.Should be a JSON-encoded string using jsonencode()
        /// </summary>
        [Output("scopeSelector")]
        public Output<string?> ScopeSelector { get; private set; } = null!;

        /// <summary>
        /// The GUID of the tenant that the K8's quota will be created in.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;


        /// <summary>
        /// Create a TenantK8sResourceQuota resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TenantK8sResourceQuota(string name, TenantK8sResourceQuotaArgs args, CustomResourceOptions? options = null)
            : base("duplocloud:index/tenantK8sResourceQuota:TenantK8sResourceQuota", name, args ?? new TenantK8sResourceQuotaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TenantK8sResourceQuota(string name, Input<string> id, TenantK8sResourceQuotaState? state = null, CustomResourceOptions? options = null)
            : base("duplocloud:index/tenantK8sResourceQuota:TenantK8sResourceQuota", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/duplocloud/pulumi-duplocloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TenantK8sResourceQuota resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TenantK8sResourceQuota Get(string name, Input<string> id, TenantK8sResourceQuotaState? state = null, CustomResourceOptions? options = null)
        {
            return new TenantK8sResourceQuota(name, id, state, options);
        }
    }

    public sealed class TenantK8sResourceQuotaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the K8's quota.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Limits the total amount of compute, storage, and object resources that a namespace can use to prevent over-consumption and ensure fair resource allocation in a Kubernetes cluster. Should be a JSON-encoded string using jsonencode()
        /// </summary>
        [Input("resourceQuota", required: true)]
        public Input<string> ResourceQuota { get; set; } = null!;

        /// <summary>
        /// Applies quota only to resources matching specified workload scopes.Should be a JSON-encoded string using jsonencode()
        /// </summary>
        [Input("scopeSelector")]
        public Input<string>? ScopeSelector { get; set; }

        /// <summary>
        /// The GUID of the tenant that the K8's quota will be created in.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public TenantK8sResourceQuotaArgs()
        {
        }
        public static new TenantK8sResourceQuotaArgs Empty => new TenantK8sResourceQuotaArgs();
    }

    public sealed class TenantK8sResourceQuotaState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the K8's quota.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Limits the total amount of compute, storage, and object resources that a namespace can use to prevent over-consumption and ensure fair resource allocation in a Kubernetes cluster. Should be a JSON-encoded string using jsonencode()
        /// </summary>
        [Input("resourceQuota")]
        public Input<string>? ResourceQuota { get; set; }

        /// <summary>
        /// Applies quota only to resources matching specified workload scopes.Should be a JSON-encoded string using jsonencode()
        /// </summary>
        [Input("scopeSelector")]
        public Input<string>? ScopeSelector { get; set; }

        /// <summary>
        /// The GUID of the tenant that the K8's quota will be created in.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        public TenantK8sResourceQuotaState()
        {
        }
        public static new TenantK8sResourceQuotaState Empty => new TenantK8sResourceQuotaState();
    }
}
