// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package duplocloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// `AwsCloudfrontDistribution` manages an aws cloudfront distribution in Duplo.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := duplocloud.NewTenant(ctx, "duplo-app", &duplocloud.TenantArgs{
//				AccountName: pulumi.String("duplo-app"),
//				PlanId:      pulumi.String("default"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = duplocloud.NewAwsCloudfrontDistribution(ctx, "cfd", &duplocloud.AwsCloudfrontDistributionArgs{
//				TenantId:          duplo_app.TenantId,
//				Comment:           pulumi.String("duploservices-dev01-app"),
//				DefaultRootObject: pulumi.String("index.html"),
//				Enabled:           pulumi.Bool(true),
//				HttpVersion:       pulumi.String("http2"),
//				IsIpv6Enabled:     pulumi.Bool(true),
//				Aliases: pulumi.StringArray{
//					pulumi.String("app-dev.abc.xyz"),
//				},
//				PriceClass:        pulumi.String("PriceClass_All"),
//				WaitForDeployment: pulumi.Bool(true),
//				Origins: duplocloud.AwsCloudfrontDistributionOriginArray{
//					&duplocloud.AwsCloudfrontDistributionOriginArgs{
//						DomainName:         pulumi.String("pa-api-dev01.abc.xyz"),
//						OriginId:           pulumi.String("pa-api-dev01.abc.xyz"),
//						ConnectionAttempts: pulumi.Int(3),
//						ConnectionTimeout:  pulumi.Int(10),
//						CustomOriginConfig: &duplocloud.AwsCloudfrontDistributionOriginCustomOriginConfigArgs{
//							HttpPort:               pulumi.Int(80),
//							HttpsPort:              pulumi.Int(443),
//							OriginKeepaliveTimeout: pulumi.Int(30),
//							OriginReadTimeout:      pulumi.Int(30),
//							OriginProtocolPolicy:   pulumi.String("https-only"),
//							OriginSslProtocols: pulumi.StringArray{
//								pulumi.String("TLSv1.2"),
//							},
//						},
//					},
//					&duplocloud.AwsCloudfrontDistributionOriginArgs{
//						DomainName:         pulumi.String("duploservices-dev01-abc-app-1234567890.s3.us-west-2.amazonaws.com"),
//						OriginId:           pulumi.String("duploservices-dev01-abc-app-1234567890.s3.us-west-2.amazonaws.com"),
//						ConnectionAttempts: pulumi.Int(3),
//						ConnectionTimeout:  pulumi.Int(10),
//					},
//				},
//				DefaultCacheBehavior: &duplocloud.AwsCloudfrontDistributionDefaultCacheBehaviorArgs{
//					AllowedMethods: pulumi.StringArray{
//						pulumi.String("GET"),
//						pulumi.String("HEAD"),
//					},
//					CachedMethods: pulumi.StringArray{
//						pulumi.String("GET"),
//						pulumi.String("HEAD"),
//					},
//					TargetOriginId:       pulumi.String("duploservices-dev01-abc-app-1234567890.s3.us-west-2.amazonaws.com"),
//					Compress:             pulumi.Bool(false),
//					ViewerProtocolPolicy: pulumi.String("redirect-to-https"),
//					MinTtl:               pulumi.Int(0),
//					DefaultTtl:           pulumi.Int(0),
//					MaxTtl:               pulumi.Int(0),
//				},
//				OrderedCacheBehaviors: duplocloud.AwsCloudfrontDistributionOrderedCacheBehaviorArray{
//					&duplocloud.AwsCloudfrontDistributionOrderedCacheBehaviorArgs{
//						AllowedMethods: pulumi.StringArray{
//							pulumi.String("GET"),
//							pulumi.String("HEAD"),
//						},
//						CachedMethods: pulumi.StringArray{
//							pulumi.String("GET"),
//							pulumi.String("HEAD"),
//						},
//						TargetOriginId:       pulumi.String("pa-api-dev01.abc.xyz"),
//						Compress:             pulumi.Bool(false),
//						ViewerProtocolPolicy: pulumi.String("redirect-to-https"),
//						MinTtl:               pulumi.Int(0),
//						DefaultTtl:           pulumi.Int(0),
//						MaxTtl:               pulumi.Int(0),
//						PathPattern:          pulumi.String("/api/*"),
//					},
//				},
//				ViewerCertificate: &duplocloud.AwsCloudfrontDistributionViewerCertificateArgs{
//					AcmCertificateArn:      pulumi.String("arn:aws:acm:us-east-1:1234567890:certificate/49c7a151-14b1-486e-801f-cf6bc9a43804"),
//					MinimumProtocolVersion: pulumi.String("TLSv1.2_2019"),
//					SslSupportMethod:       pulumi.String("sni-only"),
//				},
//				Restrictions: &duplocloud.AwsCloudfrontDistributionRestrictionsArgs{
//					GeoRestriction: &duplocloud.AwsCloudfrontDistributionRestrictionsGeoRestrictionArgs{
//						RestrictionType: pulumi.String("none"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Example: Importing an existing AWS Cloudfront Distribution
//
//   - *TENANT_ID* is the tenant GUID
//
//   - *CLOUDFRONT_ID* is the cloudfront id
//
// #
//
// ```sh
// $ pulumi import duplocloud:index/awsCloudfrontDistribution:AwsCloudfrontDistribution myCFD *TENANT_ID*/*CLOUDFRONT_ID*
// ```
type AwsCloudfrontDistribution struct {
	pulumi.CustomResourceState

	// Extra CNAMEs (alternate domain names), if any, for this distribution.
	Aliases pulumi.StringArrayOutput `pulumi:"aliases"`
	Arn     pulumi.StringOutput      `pulumi:"arn"`
	// Any comments you want to include about the distribution. comment has been deprecated instead use name
	//
	// Deprecated: comment has been deprecated instead use name
	Comment              pulumi.StringOutput                                     `pulumi:"comment"`
	CorsAllowedHostNames pulumi.StringArrayOutput                                `pulumi:"corsAllowedHostNames"`
	CustomErrorResponses AwsCloudfrontDistributionCustomErrorResponseArrayOutput `pulumi:"customErrorResponses"`
	DefaultCacheBehavior AwsCloudfrontDistributionDefaultCacheBehaviorOutput     `pulumi:"defaultCacheBehavior"`
	// The object that you want CloudFront to return (for example, index.html) when an end user requests the root URL.
	DefaultRootObject pulumi.StringOutput `pulumi:"defaultRootObject"`
	DomainName        pulumi.StringOutput `pulumi:"domainName"`
	// Whether the distribution is enabled to accept end user requests for content.
	Enabled      pulumi.BoolOutput   `pulumi:"enabled"`
	Etag         pulumi.StringOutput `pulumi:"etag"`
	HostedZoneId pulumi.StringOutput `pulumi:"hostedZoneId"`
	// The maximum HTTP version to support on the distribution. Allowed values are `http1.1` and `http2` Defaults to `http2`.
	HttpVersion pulumi.StringPtrOutput `pulumi:"httpVersion"`
	// Defaults to `false`.
	IsIpv6Enabled pulumi.BoolPtrOutput                            `pulumi:"isIpv6Enabled"`
	LoggingConfig AwsCloudfrontDistributionLoggingConfigPtrOutput `pulumi:"loggingConfig"`
	// Name of the distribution
	Name                  pulumi.StringOutput                                      `pulumi:"name"`
	OrderedCacheBehaviors AwsCloudfrontDistributionOrderedCacheBehaviorArrayOutput `pulumi:"orderedCacheBehaviors"`
	OriginGroups          AwsCloudfrontDistributionOriginGroupArrayOutput          `pulumi:"originGroups"`
	Origins               AwsCloudfrontDistributionOriginArrayOutput               `pulumi:"origins"`
	// The price class for this distribution. One of `PriceClass_All`, `PriceClass_200`, `PriceClass_100` Defaults to `PriceClass_All`.
	PriceClass   pulumi.StringPtrOutput                      `pulumi:"priceClass"`
	Restrictions AwsCloudfrontDistributionRestrictionsOutput `pulumi:"restrictions"`
	// The current status of the distribution. `Deployed` if the distribution's information is fully propagated throughout the Amazon CloudFront system.
	Status pulumi.StringOutput `pulumi:"status"`
	// The GUID of the tenant that the aws cloudfront distribution will be created in.
	TenantId pulumi.StringOutput `pulumi:"tenantId"`
	// Defaults to `true`.
	UseOriginAccessIdentity pulumi.BoolPtrOutput                             `pulumi:"useOriginAccessIdentity"`
	ViewerCertificate       AwsCloudfrontDistributionViewerCertificateOutput `pulumi:"viewerCertificate"`
	// Defaults to `true`.
	WaitForDeployment pulumi.BoolPtrOutput `pulumi:"waitForDeployment"`
	// A unique identifier that specifies the AWS WAF web ACL, if any, to associate with this distribution.
	WebAclId pulumi.StringOutput `pulumi:"webAclId"`
}

// NewAwsCloudfrontDistribution registers a new resource with the given unique name, arguments, and options.
func NewAwsCloudfrontDistribution(ctx *pulumi.Context,
	name string, args *AwsCloudfrontDistributionArgs, opts ...pulumi.ResourceOption) (*AwsCloudfrontDistribution, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DefaultCacheBehavior == nil {
		return nil, errors.New("invalid value for required argument 'DefaultCacheBehavior'")
	}
	if args.Enabled == nil {
		return nil, errors.New("invalid value for required argument 'Enabled'")
	}
	if args.Origins == nil {
		return nil, errors.New("invalid value for required argument 'Origins'")
	}
	if args.TenantId == nil {
		return nil, errors.New("invalid value for required argument 'TenantId'")
	}
	if args.ViewerCertificate == nil {
		return nil, errors.New("invalid value for required argument 'ViewerCertificate'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AwsCloudfrontDistribution
	err := ctx.RegisterResource("duplocloud:index/awsCloudfrontDistribution:AwsCloudfrontDistribution", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAwsCloudfrontDistribution gets an existing AwsCloudfrontDistribution resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAwsCloudfrontDistribution(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AwsCloudfrontDistributionState, opts ...pulumi.ResourceOption) (*AwsCloudfrontDistribution, error) {
	var resource AwsCloudfrontDistribution
	err := ctx.ReadResource("duplocloud:index/awsCloudfrontDistribution:AwsCloudfrontDistribution", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AwsCloudfrontDistribution resources.
type awsCloudfrontDistributionState struct {
	// Extra CNAMEs (alternate domain names), if any, for this distribution.
	Aliases []string `pulumi:"aliases"`
	Arn     *string  `pulumi:"arn"`
	// Any comments you want to include about the distribution. comment has been deprecated instead use name
	//
	// Deprecated: comment has been deprecated instead use name
	Comment              *string                                        `pulumi:"comment"`
	CorsAllowedHostNames []string                                       `pulumi:"corsAllowedHostNames"`
	CustomErrorResponses []AwsCloudfrontDistributionCustomErrorResponse `pulumi:"customErrorResponses"`
	DefaultCacheBehavior *AwsCloudfrontDistributionDefaultCacheBehavior `pulumi:"defaultCacheBehavior"`
	// The object that you want CloudFront to return (for example, index.html) when an end user requests the root URL.
	DefaultRootObject *string `pulumi:"defaultRootObject"`
	DomainName        *string `pulumi:"domainName"`
	// Whether the distribution is enabled to accept end user requests for content.
	Enabled      *bool   `pulumi:"enabled"`
	Etag         *string `pulumi:"etag"`
	HostedZoneId *string `pulumi:"hostedZoneId"`
	// The maximum HTTP version to support on the distribution. Allowed values are `http1.1` and `http2` Defaults to `http2`.
	HttpVersion *string `pulumi:"httpVersion"`
	// Defaults to `false`.
	IsIpv6Enabled *bool                                   `pulumi:"isIpv6Enabled"`
	LoggingConfig *AwsCloudfrontDistributionLoggingConfig `pulumi:"loggingConfig"`
	// Name of the distribution
	Name                  *string                                         `pulumi:"name"`
	OrderedCacheBehaviors []AwsCloudfrontDistributionOrderedCacheBehavior `pulumi:"orderedCacheBehaviors"`
	OriginGroups          []AwsCloudfrontDistributionOriginGroup          `pulumi:"originGroups"`
	Origins               []AwsCloudfrontDistributionOrigin               `pulumi:"origins"`
	// The price class for this distribution. One of `PriceClass_All`, `PriceClass_200`, `PriceClass_100` Defaults to `PriceClass_All`.
	PriceClass   *string                                `pulumi:"priceClass"`
	Restrictions *AwsCloudfrontDistributionRestrictions `pulumi:"restrictions"`
	// The current status of the distribution. `Deployed` if the distribution's information is fully propagated throughout the Amazon CloudFront system.
	Status *string `pulumi:"status"`
	// The GUID of the tenant that the aws cloudfront distribution will be created in.
	TenantId *string `pulumi:"tenantId"`
	// Defaults to `true`.
	UseOriginAccessIdentity *bool                                       `pulumi:"useOriginAccessIdentity"`
	ViewerCertificate       *AwsCloudfrontDistributionViewerCertificate `pulumi:"viewerCertificate"`
	// Defaults to `true`.
	WaitForDeployment *bool `pulumi:"waitForDeployment"`
	// A unique identifier that specifies the AWS WAF web ACL, if any, to associate with this distribution.
	WebAclId *string `pulumi:"webAclId"`
}

type AwsCloudfrontDistributionState struct {
	// Extra CNAMEs (alternate domain names), if any, for this distribution.
	Aliases pulumi.StringArrayInput
	Arn     pulumi.StringPtrInput
	// Any comments you want to include about the distribution. comment has been deprecated instead use name
	//
	// Deprecated: comment has been deprecated instead use name
	Comment              pulumi.StringPtrInput
	CorsAllowedHostNames pulumi.StringArrayInput
	CustomErrorResponses AwsCloudfrontDistributionCustomErrorResponseArrayInput
	DefaultCacheBehavior AwsCloudfrontDistributionDefaultCacheBehaviorPtrInput
	// The object that you want CloudFront to return (for example, index.html) when an end user requests the root URL.
	DefaultRootObject pulumi.StringPtrInput
	DomainName        pulumi.StringPtrInput
	// Whether the distribution is enabled to accept end user requests for content.
	Enabled      pulumi.BoolPtrInput
	Etag         pulumi.StringPtrInput
	HostedZoneId pulumi.StringPtrInput
	// The maximum HTTP version to support on the distribution. Allowed values are `http1.1` and `http2` Defaults to `http2`.
	HttpVersion pulumi.StringPtrInput
	// Defaults to `false`.
	IsIpv6Enabled pulumi.BoolPtrInput
	LoggingConfig AwsCloudfrontDistributionLoggingConfigPtrInput
	// Name of the distribution
	Name                  pulumi.StringPtrInput
	OrderedCacheBehaviors AwsCloudfrontDistributionOrderedCacheBehaviorArrayInput
	OriginGroups          AwsCloudfrontDistributionOriginGroupArrayInput
	Origins               AwsCloudfrontDistributionOriginArrayInput
	// The price class for this distribution. One of `PriceClass_All`, `PriceClass_200`, `PriceClass_100` Defaults to `PriceClass_All`.
	PriceClass   pulumi.StringPtrInput
	Restrictions AwsCloudfrontDistributionRestrictionsPtrInput
	// The current status of the distribution. `Deployed` if the distribution's information is fully propagated throughout the Amazon CloudFront system.
	Status pulumi.StringPtrInput
	// The GUID of the tenant that the aws cloudfront distribution will be created in.
	TenantId pulumi.StringPtrInput
	// Defaults to `true`.
	UseOriginAccessIdentity pulumi.BoolPtrInput
	ViewerCertificate       AwsCloudfrontDistributionViewerCertificatePtrInput
	// Defaults to `true`.
	WaitForDeployment pulumi.BoolPtrInput
	// A unique identifier that specifies the AWS WAF web ACL, if any, to associate with this distribution.
	WebAclId pulumi.StringPtrInput
}

func (AwsCloudfrontDistributionState) ElementType() reflect.Type {
	return reflect.TypeOf((*awsCloudfrontDistributionState)(nil)).Elem()
}

type awsCloudfrontDistributionArgs struct {
	// Extra CNAMEs (alternate domain names), if any, for this distribution.
	Aliases []string `pulumi:"aliases"`
	// Any comments you want to include about the distribution. comment has been deprecated instead use name
	//
	// Deprecated: comment has been deprecated instead use name
	Comment              *string                                        `pulumi:"comment"`
	CorsAllowedHostNames []string                                       `pulumi:"corsAllowedHostNames"`
	CustomErrorResponses []AwsCloudfrontDistributionCustomErrorResponse `pulumi:"customErrorResponses"`
	DefaultCacheBehavior AwsCloudfrontDistributionDefaultCacheBehavior  `pulumi:"defaultCacheBehavior"`
	// The object that you want CloudFront to return (for example, index.html) when an end user requests the root URL.
	DefaultRootObject *string `pulumi:"defaultRootObject"`
	// Whether the distribution is enabled to accept end user requests for content.
	Enabled bool `pulumi:"enabled"`
	// The maximum HTTP version to support on the distribution. Allowed values are `http1.1` and `http2` Defaults to `http2`.
	HttpVersion *string `pulumi:"httpVersion"`
	// Defaults to `false`.
	IsIpv6Enabled *bool                                   `pulumi:"isIpv6Enabled"`
	LoggingConfig *AwsCloudfrontDistributionLoggingConfig `pulumi:"loggingConfig"`
	// Name of the distribution
	Name                  *string                                         `pulumi:"name"`
	OrderedCacheBehaviors []AwsCloudfrontDistributionOrderedCacheBehavior `pulumi:"orderedCacheBehaviors"`
	OriginGroups          []AwsCloudfrontDistributionOriginGroup          `pulumi:"originGroups"`
	Origins               []AwsCloudfrontDistributionOrigin               `pulumi:"origins"`
	// The price class for this distribution. One of `PriceClass_All`, `PriceClass_200`, `PriceClass_100` Defaults to `PriceClass_All`.
	PriceClass   *string                                `pulumi:"priceClass"`
	Restrictions *AwsCloudfrontDistributionRestrictions `pulumi:"restrictions"`
	// The GUID of the tenant that the aws cloudfront distribution will be created in.
	TenantId string `pulumi:"tenantId"`
	// Defaults to `true`.
	UseOriginAccessIdentity *bool                                      `pulumi:"useOriginAccessIdentity"`
	ViewerCertificate       AwsCloudfrontDistributionViewerCertificate `pulumi:"viewerCertificate"`
	// Defaults to `true`.
	WaitForDeployment *bool `pulumi:"waitForDeployment"`
	// A unique identifier that specifies the AWS WAF web ACL, if any, to associate with this distribution.
	WebAclId *string `pulumi:"webAclId"`
}

// The set of arguments for constructing a AwsCloudfrontDistribution resource.
type AwsCloudfrontDistributionArgs struct {
	// Extra CNAMEs (alternate domain names), if any, for this distribution.
	Aliases pulumi.StringArrayInput
	// Any comments you want to include about the distribution. comment has been deprecated instead use name
	//
	// Deprecated: comment has been deprecated instead use name
	Comment              pulumi.StringPtrInput
	CorsAllowedHostNames pulumi.StringArrayInput
	CustomErrorResponses AwsCloudfrontDistributionCustomErrorResponseArrayInput
	DefaultCacheBehavior AwsCloudfrontDistributionDefaultCacheBehaviorInput
	// The object that you want CloudFront to return (for example, index.html) when an end user requests the root URL.
	DefaultRootObject pulumi.StringPtrInput
	// Whether the distribution is enabled to accept end user requests for content.
	Enabled pulumi.BoolInput
	// The maximum HTTP version to support on the distribution. Allowed values are `http1.1` and `http2` Defaults to `http2`.
	HttpVersion pulumi.StringPtrInput
	// Defaults to `false`.
	IsIpv6Enabled pulumi.BoolPtrInput
	LoggingConfig AwsCloudfrontDistributionLoggingConfigPtrInput
	// Name of the distribution
	Name                  pulumi.StringPtrInput
	OrderedCacheBehaviors AwsCloudfrontDistributionOrderedCacheBehaviorArrayInput
	OriginGroups          AwsCloudfrontDistributionOriginGroupArrayInput
	Origins               AwsCloudfrontDistributionOriginArrayInput
	// The price class for this distribution. One of `PriceClass_All`, `PriceClass_200`, `PriceClass_100` Defaults to `PriceClass_All`.
	PriceClass   pulumi.StringPtrInput
	Restrictions AwsCloudfrontDistributionRestrictionsPtrInput
	// The GUID of the tenant that the aws cloudfront distribution will be created in.
	TenantId pulumi.StringInput
	// Defaults to `true`.
	UseOriginAccessIdentity pulumi.BoolPtrInput
	ViewerCertificate       AwsCloudfrontDistributionViewerCertificateInput
	// Defaults to `true`.
	WaitForDeployment pulumi.BoolPtrInput
	// A unique identifier that specifies the AWS WAF web ACL, if any, to associate with this distribution.
	WebAclId pulumi.StringPtrInput
}

func (AwsCloudfrontDistributionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*awsCloudfrontDistributionArgs)(nil)).Elem()
}

type AwsCloudfrontDistributionInput interface {
	pulumi.Input

	ToAwsCloudfrontDistributionOutput() AwsCloudfrontDistributionOutput
	ToAwsCloudfrontDistributionOutputWithContext(ctx context.Context) AwsCloudfrontDistributionOutput
}

func (*AwsCloudfrontDistribution) ElementType() reflect.Type {
	return reflect.TypeOf((**AwsCloudfrontDistribution)(nil)).Elem()
}

func (i *AwsCloudfrontDistribution) ToAwsCloudfrontDistributionOutput() AwsCloudfrontDistributionOutput {
	return i.ToAwsCloudfrontDistributionOutputWithContext(context.Background())
}

func (i *AwsCloudfrontDistribution) ToAwsCloudfrontDistributionOutputWithContext(ctx context.Context) AwsCloudfrontDistributionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsCloudfrontDistributionOutput)
}

// AwsCloudfrontDistributionArrayInput is an input type that accepts AwsCloudfrontDistributionArray and AwsCloudfrontDistributionArrayOutput values.
// You can construct a concrete instance of `AwsCloudfrontDistributionArrayInput` via:
//
//	AwsCloudfrontDistributionArray{ AwsCloudfrontDistributionArgs{...} }
type AwsCloudfrontDistributionArrayInput interface {
	pulumi.Input

	ToAwsCloudfrontDistributionArrayOutput() AwsCloudfrontDistributionArrayOutput
	ToAwsCloudfrontDistributionArrayOutputWithContext(context.Context) AwsCloudfrontDistributionArrayOutput
}

type AwsCloudfrontDistributionArray []AwsCloudfrontDistributionInput

func (AwsCloudfrontDistributionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AwsCloudfrontDistribution)(nil)).Elem()
}

func (i AwsCloudfrontDistributionArray) ToAwsCloudfrontDistributionArrayOutput() AwsCloudfrontDistributionArrayOutput {
	return i.ToAwsCloudfrontDistributionArrayOutputWithContext(context.Background())
}

func (i AwsCloudfrontDistributionArray) ToAwsCloudfrontDistributionArrayOutputWithContext(ctx context.Context) AwsCloudfrontDistributionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsCloudfrontDistributionArrayOutput)
}

// AwsCloudfrontDistributionMapInput is an input type that accepts AwsCloudfrontDistributionMap and AwsCloudfrontDistributionMapOutput values.
// You can construct a concrete instance of `AwsCloudfrontDistributionMapInput` via:
//
//	AwsCloudfrontDistributionMap{ "key": AwsCloudfrontDistributionArgs{...} }
type AwsCloudfrontDistributionMapInput interface {
	pulumi.Input

	ToAwsCloudfrontDistributionMapOutput() AwsCloudfrontDistributionMapOutput
	ToAwsCloudfrontDistributionMapOutputWithContext(context.Context) AwsCloudfrontDistributionMapOutput
}

type AwsCloudfrontDistributionMap map[string]AwsCloudfrontDistributionInput

func (AwsCloudfrontDistributionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AwsCloudfrontDistribution)(nil)).Elem()
}

func (i AwsCloudfrontDistributionMap) ToAwsCloudfrontDistributionMapOutput() AwsCloudfrontDistributionMapOutput {
	return i.ToAwsCloudfrontDistributionMapOutputWithContext(context.Background())
}

func (i AwsCloudfrontDistributionMap) ToAwsCloudfrontDistributionMapOutputWithContext(ctx context.Context) AwsCloudfrontDistributionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsCloudfrontDistributionMapOutput)
}

type AwsCloudfrontDistributionOutput struct{ *pulumi.OutputState }

func (AwsCloudfrontDistributionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AwsCloudfrontDistribution)(nil)).Elem()
}

func (o AwsCloudfrontDistributionOutput) ToAwsCloudfrontDistributionOutput() AwsCloudfrontDistributionOutput {
	return o
}

func (o AwsCloudfrontDistributionOutput) ToAwsCloudfrontDistributionOutputWithContext(ctx context.Context) AwsCloudfrontDistributionOutput {
	return o
}

// Extra CNAMEs (alternate domain names), if any, for this distribution.
func (o AwsCloudfrontDistributionOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringArrayOutput { return v.Aliases }).(pulumi.StringArrayOutput)
}

func (o AwsCloudfrontDistributionOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.Arn }).(pulumi.StringOutput)
}

// Any comments you want to include about the distribution. comment has been deprecated instead use name
//
// Deprecated: comment has been deprecated instead use name
func (o AwsCloudfrontDistributionOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.Comment }).(pulumi.StringOutput)
}

func (o AwsCloudfrontDistributionOutput) CorsAllowedHostNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringArrayOutput { return v.CorsAllowedHostNames }).(pulumi.StringArrayOutput)
}

func (o AwsCloudfrontDistributionOutput) CustomErrorResponses() AwsCloudfrontDistributionCustomErrorResponseArrayOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionCustomErrorResponseArrayOutput {
		return v.CustomErrorResponses
	}).(AwsCloudfrontDistributionCustomErrorResponseArrayOutput)
}

func (o AwsCloudfrontDistributionOutput) DefaultCacheBehavior() AwsCloudfrontDistributionDefaultCacheBehaviorOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionDefaultCacheBehaviorOutput {
		return v.DefaultCacheBehavior
	}).(AwsCloudfrontDistributionDefaultCacheBehaviorOutput)
}

// The object that you want CloudFront to return (for example, index.html) when an end user requests the root URL.
func (o AwsCloudfrontDistributionOutput) DefaultRootObject() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.DefaultRootObject }).(pulumi.StringOutput)
}

func (o AwsCloudfrontDistributionOutput) DomainName() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.DomainName }).(pulumi.StringOutput)
}

// Whether the distribution is enabled to accept end user requests for content.
func (o AwsCloudfrontDistributionOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

func (o AwsCloudfrontDistributionOutput) Etag() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.Etag }).(pulumi.StringOutput)
}

func (o AwsCloudfrontDistributionOutput) HostedZoneId() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.HostedZoneId }).(pulumi.StringOutput)
}

// The maximum HTTP version to support on the distribution. Allowed values are `http1.1` and `http2` Defaults to `http2`.
func (o AwsCloudfrontDistributionOutput) HttpVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringPtrOutput { return v.HttpVersion }).(pulumi.StringPtrOutput)
}

// Defaults to `false`.
func (o AwsCloudfrontDistributionOutput) IsIpv6Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.BoolPtrOutput { return v.IsIpv6Enabled }).(pulumi.BoolPtrOutput)
}

func (o AwsCloudfrontDistributionOutput) LoggingConfig() AwsCloudfrontDistributionLoggingConfigPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionLoggingConfigPtrOutput {
		return v.LoggingConfig
	}).(AwsCloudfrontDistributionLoggingConfigPtrOutput)
}

// Name of the distribution
func (o AwsCloudfrontDistributionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o AwsCloudfrontDistributionOutput) OrderedCacheBehaviors() AwsCloudfrontDistributionOrderedCacheBehaviorArrayOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionOrderedCacheBehaviorArrayOutput {
		return v.OrderedCacheBehaviors
	}).(AwsCloudfrontDistributionOrderedCacheBehaviorArrayOutput)
}

func (o AwsCloudfrontDistributionOutput) OriginGroups() AwsCloudfrontDistributionOriginGroupArrayOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionOriginGroupArrayOutput {
		return v.OriginGroups
	}).(AwsCloudfrontDistributionOriginGroupArrayOutput)
}

func (o AwsCloudfrontDistributionOutput) Origins() AwsCloudfrontDistributionOriginArrayOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionOriginArrayOutput { return v.Origins }).(AwsCloudfrontDistributionOriginArrayOutput)
}

// The price class for this distribution. One of `PriceClass_All`, `PriceClass_200`, `PriceClass_100` Defaults to `PriceClass_All`.
func (o AwsCloudfrontDistributionOutput) PriceClass() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringPtrOutput { return v.PriceClass }).(pulumi.StringPtrOutput)
}

func (o AwsCloudfrontDistributionOutput) Restrictions() AwsCloudfrontDistributionRestrictionsOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionRestrictionsOutput { return v.Restrictions }).(AwsCloudfrontDistributionRestrictionsOutput)
}

// The current status of the distribution. `Deployed` if the distribution's information is fully propagated throughout the Amazon CloudFront system.
func (o AwsCloudfrontDistributionOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// The GUID of the tenant that the aws cloudfront distribution will be created in.
func (o AwsCloudfrontDistributionOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

// Defaults to `true`.
func (o AwsCloudfrontDistributionOutput) UseOriginAccessIdentity() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.BoolPtrOutput { return v.UseOriginAccessIdentity }).(pulumi.BoolPtrOutput)
}

func (o AwsCloudfrontDistributionOutput) ViewerCertificate() AwsCloudfrontDistributionViewerCertificateOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) AwsCloudfrontDistributionViewerCertificateOutput {
		return v.ViewerCertificate
	}).(AwsCloudfrontDistributionViewerCertificateOutput)
}

// Defaults to `true`.
func (o AwsCloudfrontDistributionOutput) WaitForDeployment() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.BoolPtrOutput { return v.WaitForDeployment }).(pulumi.BoolPtrOutput)
}

// A unique identifier that specifies the AWS WAF web ACL, if any, to associate with this distribution.
func (o AwsCloudfrontDistributionOutput) WebAclId() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontDistribution) pulumi.StringOutput { return v.WebAclId }).(pulumi.StringOutput)
}

type AwsCloudfrontDistributionArrayOutput struct{ *pulumi.OutputState }

func (AwsCloudfrontDistributionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AwsCloudfrontDistribution)(nil)).Elem()
}

func (o AwsCloudfrontDistributionArrayOutput) ToAwsCloudfrontDistributionArrayOutput() AwsCloudfrontDistributionArrayOutput {
	return o
}

func (o AwsCloudfrontDistributionArrayOutput) ToAwsCloudfrontDistributionArrayOutputWithContext(ctx context.Context) AwsCloudfrontDistributionArrayOutput {
	return o
}

func (o AwsCloudfrontDistributionArrayOutput) Index(i pulumi.IntInput) AwsCloudfrontDistributionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AwsCloudfrontDistribution {
		return vs[0].([]*AwsCloudfrontDistribution)[vs[1].(int)]
	}).(AwsCloudfrontDistributionOutput)
}

type AwsCloudfrontDistributionMapOutput struct{ *pulumi.OutputState }

func (AwsCloudfrontDistributionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AwsCloudfrontDistribution)(nil)).Elem()
}

func (o AwsCloudfrontDistributionMapOutput) ToAwsCloudfrontDistributionMapOutput() AwsCloudfrontDistributionMapOutput {
	return o
}

func (o AwsCloudfrontDistributionMapOutput) ToAwsCloudfrontDistributionMapOutputWithContext(ctx context.Context) AwsCloudfrontDistributionMapOutput {
	return o
}

func (o AwsCloudfrontDistributionMapOutput) MapIndex(k pulumi.StringInput) AwsCloudfrontDistributionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AwsCloudfrontDistribution {
		return vs[0].(map[string]*AwsCloudfrontDistribution)[vs[1].(string)]
	}).(AwsCloudfrontDistributionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AwsCloudfrontDistributionInput)(nil)).Elem(), &AwsCloudfrontDistribution{})
	pulumi.RegisterInputType(reflect.TypeOf((*AwsCloudfrontDistributionArrayInput)(nil)).Elem(), AwsCloudfrontDistributionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AwsCloudfrontDistributionMapInput)(nil)).Elem(), AwsCloudfrontDistributionMap{})
	pulumi.RegisterOutputType(AwsCloudfrontDistributionOutput{})
	pulumi.RegisterOutputType(AwsCloudfrontDistributionArrayOutput{})
	pulumi.RegisterOutputType(AwsCloudfrontDistributionMapOutput{})
}
