// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package duplocloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// duplocloud_aws_cloudfront_function allows you to create and manage AWS CloudFront Functions in DuploCloud.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := duplocloud.NewTenant(ctx, "duplo-app", &duplocloud.TenantArgs{
//				AccountName: pulumi.String("duplo-app"),
//				PlanId:      pulumi.String("default"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = duplocloud.NewAwsCloudfrontFunction(ctx, "func", &duplocloud.AwsCloudfrontFunctionArgs{
//				TenantId: duplo_app.TenantId,
//				Name:     pulumi.String("test-cloudfront-func"),
//				Runtime:  pulumi.String("cloudfront-js-2.0"),
//				Code: pulumi.String(`function handler(event) {
//	  var request = event.request;
//	  var headers = request.headers;
//
//	  // Add a custom header
//	  headers['x-custom-header'] = { value: 'Hello from CloudFront Function!' };
//
//	  return request;
//	}
//
// `),
//
//				Comment: pulumi.String("This is a test CloudFront function"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Example: Importing an existing AWS Cloudfront Function
//
//   - *TENANT_ID* is the tenant GUID
//
//   - *SHORT_NAME* is the function name without duplo prefix
//
// #
//
// ```sh
// $ pulumi import duplocloud:index/awsCloudfrontFunction:AwsCloudfrontFunction func *TENANT_ID*/cloudfront-function/*SHORT_NAME*
// ```
type AwsCloudfrontFunction struct {
	pulumi.CustomResourceState

	// The JavaScript code for the CloudFront function.
	Code pulumi.StringOutput `pulumi:"code"`
	// A comment to describe the CloudFront function.
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// The ARN of the CloudFront function.
	FunctionArn pulumi.StringOutput `pulumi:"functionArn"`
	// The name of the CloudFront function.
	Name pulumi.StringOutput `pulumi:"name"`
	// Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
	Publish pulumi.BoolPtrOutput `pulumi:"publish"`
	// The runtime environment for the CloudFront function.
	Runtime pulumi.StringOutput `pulumi:"runtime"`
	Status  pulumi.StringOutput `pulumi:"status"`
	// The GUID of the tenant in DuploCloud.
	TenantId pulumi.StringOutput `pulumi:"tenantId"`
}

// NewAwsCloudfrontFunction registers a new resource with the given unique name, arguments, and options.
func NewAwsCloudfrontFunction(ctx *pulumi.Context,
	name string, args *AwsCloudfrontFunctionArgs, opts ...pulumi.ResourceOption) (*AwsCloudfrontFunction, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Code == nil {
		return nil, errors.New("invalid value for required argument 'Code'")
	}
	if args.Runtime == nil {
		return nil, errors.New("invalid value for required argument 'Runtime'")
	}
	if args.TenantId == nil {
		return nil, errors.New("invalid value for required argument 'TenantId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AwsCloudfrontFunction
	err := ctx.RegisterResource("duplocloud:index/awsCloudfrontFunction:AwsCloudfrontFunction", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAwsCloudfrontFunction gets an existing AwsCloudfrontFunction resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAwsCloudfrontFunction(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AwsCloudfrontFunctionState, opts ...pulumi.ResourceOption) (*AwsCloudfrontFunction, error) {
	var resource AwsCloudfrontFunction
	err := ctx.ReadResource("duplocloud:index/awsCloudfrontFunction:AwsCloudfrontFunction", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AwsCloudfrontFunction resources.
type awsCloudfrontFunctionState struct {
	// The JavaScript code for the CloudFront function.
	Code *string `pulumi:"code"`
	// A comment to describe the CloudFront function.
	Comment *string `pulumi:"comment"`
	// The ARN of the CloudFront function.
	FunctionArn *string `pulumi:"functionArn"`
	// The name of the CloudFront function.
	Name *string `pulumi:"name"`
	// Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
	Publish *bool `pulumi:"publish"`
	// The runtime environment for the CloudFront function.
	Runtime *string `pulumi:"runtime"`
	Status  *string `pulumi:"status"`
	// The GUID of the tenant in DuploCloud.
	TenantId *string `pulumi:"tenantId"`
}

type AwsCloudfrontFunctionState struct {
	// The JavaScript code for the CloudFront function.
	Code pulumi.StringPtrInput
	// A comment to describe the CloudFront function.
	Comment pulumi.StringPtrInput
	// The ARN of the CloudFront function.
	FunctionArn pulumi.StringPtrInput
	// The name of the CloudFront function.
	Name pulumi.StringPtrInput
	// Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
	Publish pulumi.BoolPtrInput
	// The runtime environment for the CloudFront function.
	Runtime pulumi.StringPtrInput
	Status  pulumi.StringPtrInput
	// The GUID of the tenant in DuploCloud.
	TenantId pulumi.StringPtrInput
}

func (AwsCloudfrontFunctionState) ElementType() reflect.Type {
	return reflect.TypeOf((*awsCloudfrontFunctionState)(nil)).Elem()
}

type awsCloudfrontFunctionArgs struct {
	// The JavaScript code for the CloudFront function.
	Code string `pulumi:"code"`
	// A comment to describe the CloudFront function.
	Comment *string `pulumi:"comment"`
	// The name of the CloudFront function.
	Name *string `pulumi:"name"`
	// Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
	Publish *bool `pulumi:"publish"`
	// The runtime environment for the CloudFront function.
	Runtime string `pulumi:"runtime"`
	// The GUID of the tenant in DuploCloud.
	TenantId string `pulumi:"tenantId"`
}

// The set of arguments for constructing a AwsCloudfrontFunction resource.
type AwsCloudfrontFunctionArgs struct {
	// The JavaScript code for the CloudFront function.
	Code pulumi.StringInput
	// A comment to describe the CloudFront function.
	Comment pulumi.StringPtrInput
	// The name of the CloudFront function.
	Name pulumi.StringPtrInput
	// Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
	Publish pulumi.BoolPtrInput
	// The runtime environment for the CloudFront function.
	Runtime pulumi.StringInput
	// The GUID of the tenant in DuploCloud.
	TenantId pulumi.StringInput
}

func (AwsCloudfrontFunctionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*awsCloudfrontFunctionArgs)(nil)).Elem()
}

type AwsCloudfrontFunctionInput interface {
	pulumi.Input

	ToAwsCloudfrontFunctionOutput() AwsCloudfrontFunctionOutput
	ToAwsCloudfrontFunctionOutputWithContext(ctx context.Context) AwsCloudfrontFunctionOutput
}

func (*AwsCloudfrontFunction) ElementType() reflect.Type {
	return reflect.TypeOf((**AwsCloudfrontFunction)(nil)).Elem()
}

func (i *AwsCloudfrontFunction) ToAwsCloudfrontFunctionOutput() AwsCloudfrontFunctionOutput {
	return i.ToAwsCloudfrontFunctionOutputWithContext(context.Background())
}

func (i *AwsCloudfrontFunction) ToAwsCloudfrontFunctionOutputWithContext(ctx context.Context) AwsCloudfrontFunctionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsCloudfrontFunctionOutput)
}

// AwsCloudfrontFunctionArrayInput is an input type that accepts AwsCloudfrontFunctionArray and AwsCloudfrontFunctionArrayOutput values.
// You can construct a concrete instance of `AwsCloudfrontFunctionArrayInput` via:
//
//	AwsCloudfrontFunctionArray{ AwsCloudfrontFunctionArgs{...} }
type AwsCloudfrontFunctionArrayInput interface {
	pulumi.Input

	ToAwsCloudfrontFunctionArrayOutput() AwsCloudfrontFunctionArrayOutput
	ToAwsCloudfrontFunctionArrayOutputWithContext(context.Context) AwsCloudfrontFunctionArrayOutput
}

type AwsCloudfrontFunctionArray []AwsCloudfrontFunctionInput

func (AwsCloudfrontFunctionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AwsCloudfrontFunction)(nil)).Elem()
}

func (i AwsCloudfrontFunctionArray) ToAwsCloudfrontFunctionArrayOutput() AwsCloudfrontFunctionArrayOutput {
	return i.ToAwsCloudfrontFunctionArrayOutputWithContext(context.Background())
}

func (i AwsCloudfrontFunctionArray) ToAwsCloudfrontFunctionArrayOutputWithContext(ctx context.Context) AwsCloudfrontFunctionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsCloudfrontFunctionArrayOutput)
}

// AwsCloudfrontFunctionMapInput is an input type that accepts AwsCloudfrontFunctionMap and AwsCloudfrontFunctionMapOutput values.
// You can construct a concrete instance of `AwsCloudfrontFunctionMapInput` via:
//
//	AwsCloudfrontFunctionMap{ "key": AwsCloudfrontFunctionArgs{...} }
type AwsCloudfrontFunctionMapInput interface {
	pulumi.Input

	ToAwsCloudfrontFunctionMapOutput() AwsCloudfrontFunctionMapOutput
	ToAwsCloudfrontFunctionMapOutputWithContext(context.Context) AwsCloudfrontFunctionMapOutput
}

type AwsCloudfrontFunctionMap map[string]AwsCloudfrontFunctionInput

func (AwsCloudfrontFunctionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AwsCloudfrontFunction)(nil)).Elem()
}

func (i AwsCloudfrontFunctionMap) ToAwsCloudfrontFunctionMapOutput() AwsCloudfrontFunctionMapOutput {
	return i.ToAwsCloudfrontFunctionMapOutputWithContext(context.Background())
}

func (i AwsCloudfrontFunctionMap) ToAwsCloudfrontFunctionMapOutputWithContext(ctx context.Context) AwsCloudfrontFunctionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsCloudfrontFunctionMapOutput)
}

type AwsCloudfrontFunctionOutput struct{ *pulumi.OutputState }

func (AwsCloudfrontFunctionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AwsCloudfrontFunction)(nil)).Elem()
}

func (o AwsCloudfrontFunctionOutput) ToAwsCloudfrontFunctionOutput() AwsCloudfrontFunctionOutput {
	return o
}

func (o AwsCloudfrontFunctionOutput) ToAwsCloudfrontFunctionOutputWithContext(ctx context.Context) AwsCloudfrontFunctionOutput {
	return o
}

// The JavaScript code for the CloudFront function.
func (o AwsCloudfrontFunctionOutput) Code() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.StringOutput { return v.Code }).(pulumi.StringOutput)
}

// A comment to describe the CloudFront function.
func (o AwsCloudfrontFunctionOutput) Comment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.StringPtrOutput { return v.Comment }).(pulumi.StringPtrOutput)
}

// The ARN of the CloudFront function.
func (o AwsCloudfrontFunctionOutput) FunctionArn() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.StringOutput { return v.FunctionArn }).(pulumi.StringOutput)
}

// The name of the CloudFront function.
func (o AwsCloudfrontFunctionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
func (o AwsCloudfrontFunctionOutput) Publish() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.BoolPtrOutput { return v.Publish }).(pulumi.BoolPtrOutput)
}

// The runtime environment for the CloudFront function.
func (o AwsCloudfrontFunctionOutput) Runtime() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.StringOutput { return v.Runtime }).(pulumi.StringOutput)
}

func (o AwsCloudfrontFunctionOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// The GUID of the tenant in DuploCloud.
func (o AwsCloudfrontFunctionOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsCloudfrontFunction) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

type AwsCloudfrontFunctionArrayOutput struct{ *pulumi.OutputState }

func (AwsCloudfrontFunctionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AwsCloudfrontFunction)(nil)).Elem()
}

func (o AwsCloudfrontFunctionArrayOutput) ToAwsCloudfrontFunctionArrayOutput() AwsCloudfrontFunctionArrayOutput {
	return o
}

func (o AwsCloudfrontFunctionArrayOutput) ToAwsCloudfrontFunctionArrayOutputWithContext(ctx context.Context) AwsCloudfrontFunctionArrayOutput {
	return o
}

func (o AwsCloudfrontFunctionArrayOutput) Index(i pulumi.IntInput) AwsCloudfrontFunctionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AwsCloudfrontFunction {
		return vs[0].([]*AwsCloudfrontFunction)[vs[1].(int)]
	}).(AwsCloudfrontFunctionOutput)
}

type AwsCloudfrontFunctionMapOutput struct{ *pulumi.OutputState }

func (AwsCloudfrontFunctionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AwsCloudfrontFunction)(nil)).Elem()
}

func (o AwsCloudfrontFunctionMapOutput) ToAwsCloudfrontFunctionMapOutput() AwsCloudfrontFunctionMapOutput {
	return o
}

func (o AwsCloudfrontFunctionMapOutput) ToAwsCloudfrontFunctionMapOutputWithContext(ctx context.Context) AwsCloudfrontFunctionMapOutput {
	return o
}

func (o AwsCloudfrontFunctionMapOutput) MapIndex(k pulumi.StringInput) AwsCloudfrontFunctionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AwsCloudfrontFunction {
		return vs[0].(map[string]*AwsCloudfrontFunction)[vs[1].(string)]
	}).(AwsCloudfrontFunctionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AwsCloudfrontFunctionInput)(nil)).Elem(), &AwsCloudfrontFunction{})
	pulumi.RegisterInputType(reflect.TypeOf((*AwsCloudfrontFunctionArrayInput)(nil)).Elem(), AwsCloudfrontFunctionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AwsCloudfrontFunctionMapInput)(nil)).Elem(), AwsCloudfrontFunctionMap{})
	pulumi.RegisterOutputType(AwsCloudfrontFunctionOutput{})
	pulumi.RegisterOutputType(AwsCloudfrontFunctionArrayOutput{})
	pulumi.RegisterOutputType(AwsCloudfrontFunctionMapOutput{})
}
