// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package duplocloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// `AwsMqConfig` manages an configuration for amazon mq managed by Duplo.
//
// ## Import
//
// Example: Importing an existing AWS MQ configuration
//
//   - *TENANT_ID* is the tenant GUID
//
//   - *BROKER_NAME* is the short name of the AWS MQ broker
//
//   - *BROKER_ID* is the broker ID of the AWS MQ broker
//
// ```sh
// $ pulumi import duplocloud:index/awsMqConfig:AwsMqConfig mqconfig *TENANT_ID*/*BROKER_ID*/*BROKER_NAME*
// ```
type AwsMqConfig struct {
	pulumi.CustomResourceState

	Arn pulumi.StringOutput `pulumi:"arn"`
	// Specify authentication strategy, valid values are `SIMPLE`, `LDAP`
	AuthenticationStrategy pulumi.StringOutput `pulumi:"authenticationStrategy"`
	ConfigurationId        pulumi.StringOutput `pulumi:"configurationId"`
	// Base64 configuration data, applicable for only updating
	Data pulumi.StringPtrOutput `pulumi:"data"`
	// Descritpion of MQ configuration, can be set only during update
	Description pulumi.StringOutput `pulumi:"description"`
	// Specify engine type, valid values are `ACTIVEMQ`, `RABBITMQ`
	EngineType pulumi.StringOutput `pulumi:"engineType"`
	// Specify valid engine version based on engine type
	EngineVersion pulumi.StringOutput `pulumi:"engineVersion"`
	Fullname      pulumi.StringOutput `pulumi:"fullname"`
	LatestVersion pulumi.IntOutput    `pulumi:"latestVersion"`
	// The name of MQ configuration.
	Name pulumi.StringOutput    `pulumi:"name"`
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// The GUID of the tenant that the custom tag for a resource will be created in.
	TenantId pulumi.StringOutput `pulumi:"tenantId"`
}

// NewAwsMqConfig registers a new resource with the given unique name, arguments, and options.
func NewAwsMqConfig(ctx *pulumi.Context,
	name string, args *AwsMqConfigArgs, opts ...pulumi.ResourceOption) (*AwsMqConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AuthenticationStrategy == nil {
		return nil, errors.New("invalid value for required argument 'AuthenticationStrategy'")
	}
	if args.EngineType == nil {
		return nil, errors.New("invalid value for required argument 'EngineType'")
	}
	if args.EngineVersion == nil {
		return nil, errors.New("invalid value for required argument 'EngineVersion'")
	}
	if args.TenantId == nil {
		return nil, errors.New("invalid value for required argument 'TenantId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AwsMqConfig
	err := ctx.RegisterResource("duplocloud:index/awsMqConfig:AwsMqConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAwsMqConfig gets an existing AwsMqConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAwsMqConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AwsMqConfigState, opts ...pulumi.ResourceOption) (*AwsMqConfig, error) {
	var resource AwsMqConfig
	err := ctx.ReadResource("duplocloud:index/awsMqConfig:AwsMqConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AwsMqConfig resources.
type awsMqConfigState struct {
	Arn *string `pulumi:"arn"`
	// Specify authentication strategy, valid values are `SIMPLE`, `LDAP`
	AuthenticationStrategy *string `pulumi:"authenticationStrategy"`
	ConfigurationId        *string `pulumi:"configurationId"`
	// Base64 configuration data, applicable for only updating
	Data *string `pulumi:"data"`
	// Descritpion of MQ configuration, can be set only during update
	Description *string `pulumi:"description"`
	// Specify engine type, valid values are `ACTIVEMQ`, `RABBITMQ`
	EngineType *string `pulumi:"engineType"`
	// Specify valid engine version based on engine type
	EngineVersion *string `pulumi:"engineVersion"`
	Fullname      *string `pulumi:"fullname"`
	LatestVersion *int    `pulumi:"latestVersion"`
	// The name of MQ configuration.
	Name *string           `pulumi:"name"`
	Tags map[string]string `pulumi:"tags"`
	// The GUID of the tenant that the custom tag for a resource will be created in.
	TenantId *string `pulumi:"tenantId"`
}

type AwsMqConfigState struct {
	Arn pulumi.StringPtrInput
	// Specify authentication strategy, valid values are `SIMPLE`, `LDAP`
	AuthenticationStrategy pulumi.StringPtrInput
	ConfigurationId        pulumi.StringPtrInput
	// Base64 configuration data, applicable for only updating
	Data pulumi.StringPtrInput
	// Descritpion of MQ configuration, can be set only during update
	Description pulumi.StringPtrInput
	// Specify engine type, valid values are `ACTIVEMQ`, `RABBITMQ`
	EngineType pulumi.StringPtrInput
	// Specify valid engine version based on engine type
	EngineVersion pulumi.StringPtrInput
	Fullname      pulumi.StringPtrInput
	LatestVersion pulumi.IntPtrInput
	// The name of MQ configuration.
	Name pulumi.StringPtrInput
	Tags pulumi.StringMapInput
	// The GUID of the tenant that the custom tag for a resource will be created in.
	TenantId pulumi.StringPtrInput
}

func (AwsMqConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*awsMqConfigState)(nil)).Elem()
}

type awsMqConfigArgs struct {
	// Specify authentication strategy, valid values are `SIMPLE`, `LDAP`
	AuthenticationStrategy string `pulumi:"authenticationStrategy"`
	// Base64 configuration data, applicable for only updating
	Data *string `pulumi:"data"`
	// Descritpion of MQ configuration, can be set only during update
	Description *string `pulumi:"description"`
	// Specify engine type, valid values are `ACTIVEMQ`, `RABBITMQ`
	EngineType string `pulumi:"engineType"`
	// Specify valid engine version based on engine type
	EngineVersion string `pulumi:"engineVersion"`
	// The name of MQ configuration.
	Name *string `pulumi:"name"`
	// The GUID of the tenant that the custom tag for a resource will be created in.
	TenantId string `pulumi:"tenantId"`
}

// The set of arguments for constructing a AwsMqConfig resource.
type AwsMqConfigArgs struct {
	// Specify authentication strategy, valid values are `SIMPLE`, `LDAP`
	AuthenticationStrategy pulumi.StringInput
	// Base64 configuration data, applicable for only updating
	Data pulumi.StringPtrInput
	// Descritpion of MQ configuration, can be set only during update
	Description pulumi.StringPtrInput
	// Specify engine type, valid values are `ACTIVEMQ`, `RABBITMQ`
	EngineType pulumi.StringInput
	// Specify valid engine version based on engine type
	EngineVersion pulumi.StringInput
	// The name of MQ configuration.
	Name pulumi.StringPtrInput
	// The GUID of the tenant that the custom tag for a resource will be created in.
	TenantId pulumi.StringInput
}

func (AwsMqConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*awsMqConfigArgs)(nil)).Elem()
}

type AwsMqConfigInput interface {
	pulumi.Input

	ToAwsMqConfigOutput() AwsMqConfigOutput
	ToAwsMqConfigOutputWithContext(ctx context.Context) AwsMqConfigOutput
}

func (*AwsMqConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**AwsMqConfig)(nil)).Elem()
}

func (i *AwsMqConfig) ToAwsMqConfigOutput() AwsMqConfigOutput {
	return i.ToAwsMqConfigOutputWithContext(context.Background())
}

func (i *AwsMqConfig) ToAwsMqConfigOutputWithContext(ctx context.Context) AwsMqConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsMqConfigOutput)
}

// AwsMqConfigArrayInput is an input type that accepts AwsMqConfigArray and AwsMqConfigArrayOutput values.
// You can construct a concrete instance of `AwsMqConfigArrayInput` via:
//
//	AwsMqConfigArray{ AwsMqConfigArgs{...} }
type AwsMqConfigArrayInput interface {
	pulumi.Input

	ToAwsMqConfigArrayOutput() AwsMqConfigArrayOutput
	ToAwsMqConfigArrayOutputWithContext(context.Context) AwsMqConfigArrayOutput
}

type AwsMqConfigArray []AwsMqConfigInput

func (AwsMqConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AwsMqConfig)(nil)).Elem()
}

func (i AwsMqConfigArray) ToAwsMqConfigArrayOutput() AwsMqConfigArrayOutput {
	return i.ToAwsMqConfigArrayOutputWithContext(context.Background())
}

func (i AwsMqConfigArray) ToAwsMqConfigArrayOutputWithContext(ctx context.Context) AwsMqConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsMqConfigArrayOutput)
}

// AwsMqConfigMapInput is an input type that accepts AwsMqConfigMap and AwsMqConfigMapOutput values.
// You can construct a concrete instance of `AwsMqConfigMapInput` via:
//
//	AwsMqConfigMap{ "key": AwsMqConfigArgs{...} }
type AwsMqConfigMapInput interface {
	pulumi.Input

	ToAwsMqConfigMapOutput() AwsMqConfigMapOutput
	ToAwsMqConfigMapOutputWithContext(context.Context) AwsMqConfigMapOutput
}

type AwsMqConfigMap map[string]AwsMqConfigInput

func (AwsMqConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AwsMqConfig)(nil)).Elem()
}

func (i AwsMqConfigMap) ToAwsMqConfigMapOutput() AwsMqConfigMapOutput {
	return i.ToAwsMqConfigMapOutputWithContext(context.Background())
}

func (i AwsMqConfigMap) ToAwsMqConfigMapOutputWithContext(ctx context.Context) AwsMqConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AwsMqConfigMapOutput)
}

type AwsMqConfigOutput struct{ *pulumi.OutputState }

func (AwsMqConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AwsMqConfig)(nil)).Elem()
}

func (o AwsMqConfigOutput) ToAwsMqConfigOutput() AwsMqConfigOutput {
	return o
}

func (o AwsMqConfigOutput) ToAwsMqConfigOutputWithContext(ctx context.Context) AwsMqConfigOutput {
	return o
}

func (o AwsMqConfigOutput) Arn() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.Arn }).(pulumi.StringOutput)
}

// Specify authentication strategy, valid values are `SIMPLE`, `LDAP`
func (o AwsMqConfigOutput) AuthenticationStrategy() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.AuthenticationStrategy }).(pulumi.StringOutput)
}

func (o AwsMqConfigOutput) ConfigurationId() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.ConfigurationId }).(pulumi.StringOutput)
}

// Base64 configuration data, applicable for only updating
func (o AwsMqConfigOutput) Data() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringPtrOutput { return v.Data }).(pulumi.StringPtrOutput)
}

// Descritpion of MQ configuration, can be set only during update
func (o AwsMqConfigOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Specify engine type, valid values are `ACTIVEMQ`, `RABBITMQ`
func (o AwsMqConfigOutput) EngineType() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.EngineType }).(pulumi.StringOutput)
}

// Specify valid engine version based on engine type
func (o AwsMqConfigOutput) EngineVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.EngineVersion }).(pulumi.StringOutput)
}

func (o AwsMqConfigOutput) Fullname() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.Fullname }).(pulumi.StringOutput)
}

func (o AwsMqConfigOutput) LatestVersion() pulumi.IntOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.IntOutput { return v.LatestVersion }).(pulumi.IntOutput)
}

// The name of MQ configuration.
func (o AwsMqConfigOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o AwsMqConfigOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// The GUID of the tenant that the custom tag for a resource will be created in.
func (o AwsMqConfigOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *AwsMqConfig) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

type AwsMqConfigArrayOutput struct{ *pulumi.OutputState }

func (AwsMqConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AwsMqConfig)(nil)).Elem()
}

func (o AwsMqConfigArrayOutput) ToAwsMqConfigArrayOutput() AwsMqConfigArrayOutput {
	return o
}

func (o AwsMqConfigArrayOutput) ToAwsMqConfigArrayOutputWithContext(ctx context.Context) AwsMqConfigArrayOutput {
	return o
}

func (o AwsMqConfigArrayOutput) Index(i pulumi.IntInput) AwsMqConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *AwsMqConfig {
		return vs[0].([]*AwsMqConfig)[vs[1].(int)]
	}).(AwsMqConfigOutput)
}

type AwsMqConfigMapOutput struct{ *pulumi.OutputState }

func (AwsMqConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AwsMqConfig)(nil)).Elem()
}

func (o AwsMqConfigMapOutput) ToAwsMqConfigMapOutput() AwsMqConfigMapOutput {
	return o
}

func (o AwsMqConfigMapOutput) ToAwsMqConfigMapOutputWithContext(ctx context.Context) AwsMqConfigMapOutput {
	return o
}

func (o AwsMqConfigMapOutput) MapIndex(k pulumi.StringInput) AwsMqConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *AwsMqConfig {
		return vs[0].(map[string]*AwsMqConfig)[vs[1].(string)]
	}).(AwsMqConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AwsMqConfigInput)(nil)).Elem(), &AwsMqConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*AwsMqConfigArrayInput)(nil)).Elem(), AwsMqConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AwsMqConfigMapInput)(nil)).Elem(), AwsMqConfigMap{})
	pulumi.RegisterOutputType(AwsMqConfigOutput{})
	pulumi.RegisterOutputType(AwsMqConfigArrayOutput{})
	pulumi.RegisterOutputType(AwsMqConfigMapOutput{})
}
