// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package duplocloud

import (
	"context"
	"reflect"

	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAwsAccount(ctx *pulumi.Context, args *GetAwsAccountArgs, opts ...pulumi.InvokeOption) (*GetAwsAccountResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAwsAccountResult
	err := ctx.Invoke("duplocloud:index/getAwsAccount:getAwsAccount", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAwsAccount.
type GetAwsAccountArgs struct {
	TenantId *string `pulumi:"tenantId"`
}

// A collection of values returned by getAwsAccount.
type GetAwsAccountResult struct {
	AccountId string `pulumi:"accountId"`
	// The provider-assigned unique ID for this managed resource.
	Id       string  `pulumi:"id"`
	TenantId *string `pulumi:"tenantId"`
}

func GetAwsAccountOutput(ctx *pulumi.Context, args GetAwsAccountOutputArgs, opts ...pulumi.InvokeOption) GetAwsAccountResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetAwsAccountResultOutput, error) {
			args := v.(GetAwsAccountArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("duplocloud:index/getAwsAccount:getAwsAccount", args, GetAwsAccountResultOutput{}, options).(GetAwsAccountResultOutput), nil
		}).(GetAwsAccountResultOutput)
}

// A collection of arguments for invoking getAwsAccount.
type GetAwsAccountOutputArgs struct {
	TenantId pulumi.StringPtrInput `pulumi:"tenantId"`
}

func (GetAwsAccountOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAwsAccountArgs)(nil)).Elem()
}

// A collection of values returned by getAwsAccount.
type GetAwsAccountResultOutput struct{ *pulumi.OutputState }

func (GetAwsAccountResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAwsAccountResult)(nil)).Elem()
}

func (o GetAwsAccountResultOutput) ToGetAwsAccountResultOutput() GetAwsAccountResultOutput {
	return o
}

func (o GetAwsAccountResultOutput) ToGetAwsAccountResultOutputWithContext(ctx context.Context) GetAwsAccountResultOutput {
	return o
}

func (o GetAwsAccountResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v GetAwsAccountResult) string { return v.AccountId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetAwsAccountResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetAwsAccountResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetAwsAccountResultOutput) TenantId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAwsAccountResult) *string { return v.TenantId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAwsAccountResultOutput{})
}
