// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package duplocloud

import (
	"context"
	"reflect"

	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			credential, err := duplocloud.GetEksCredentials(ctx, &duplocloud.GetEksCredentialsArgs{
//				PlanId: "non-prod",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("credentialValue", pulumi.StringMap{
//				"caCertificateData": credential.CaCertificateData,
//				"endpoint":          credential.Endpoint,
//				"name":              credential.Name,
//				"version":           credential.Version,
//				"region":            credential.Region,
//				"token":             credential.Token,
//			})
//			return nil
//		})
//	}
//
// ```
func GetEksCredentials(ctx *pulumi.Context, args *GetEksCredentialsArgs, opts ...pulumi.InvokeOption) (*GetEksCredentialsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetEksCredentialsResult
	err := ctx.Invoke("duplocloud:index/getEksCredentials:getEksCredentials", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEksCredentials.
type GetEksCredentialsArgs struct {
	PlanId string `pulumi:"planId"`
}

// A collection of values returned by getEksCredentials.
type GetEksCredentialsResult struct {
	CaCertificateData string `pulumi:"caCertificateData"`
	Endpoint          string `pulumi:"endpoint"`
	// The provider-assigned unique ID for this managed resource.
	Id      string `pulumi:"id"`
	Name    string `pulumi:"name"`
	PlanId  string `pulumi:"planId"`
	Region  string `pulumi:"region"`
	Token   string `pulumi:"token"`
	Version string `pulumi:"version"`
}

func GetEksCredentialsOutput(ctx *pulumi.Context, args GetEksCredentialsOutputArgs, opts ...pulumi.InvokeOption) GetEksCredentialsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEksCredentialsResultOutput, error) {
			args := v.(GetEksCredentialsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("duplocloud:index/getEksCredentials:getEksCredentials", args, GetEksCredentialsResultOutput{}, options).(GetEksCredentialsResultOutput), nil
		}).(GetEksCredentialsResultOutput)
}

// A collection of arguments for invoking getEksCredentials.
type GetEksCredentialsOutputArgs struct {
	PlanId pulumi.StringInput `pulumi:"planId"`
}

func (GetEksCredentialsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEksCredentialsArgs)(nil)).Elem()
}

// A collection of values returned by getEksCredentials.
type GetEksCredentialsResultOutput struct{ *pulumi.OutputState }

func (GetEksCredentialsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEksCredentialsResult)(nil)).Elem()
}

func (o GetEksCredentialsResultOutput) ToGetEksCredentialsResultOutput() GetEksCredentialsResultOutput {
	return o
}

func (o GetEksCredentialsResultOutput) ToGetEksCredentialsResultOutputWithContext(ctx context.Context) GetEksCredentialsResultOutput {
	return o
}

func (o GetEksCredentialsResultOutput) CaCertificateData() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.CaCertificateData }).(pulumi.StringOutput)
}

func (o GetEksCredentialsResultOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.Endpoint }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetEksCredentialsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEksCredentialsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetEksCredentialsResultOutput) PlanId() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.PlanId }).(pulumi.StringOutput)
}

func (o GetEksCredentialsResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetEksCredentialsResultOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.Token }).(pulumi.StringOutput)
}

func (o GetEksCredentialsResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksCredentialsResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEksCredentialsResultOutput{})
}
