// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package duplocloud

import (
	"context"
	"reflect"

	"github.com/duplocloud/pulumi-duplocloud/sdk/go/duplocloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupK8sDaemonSet(ctx *pulumi.Context, args *LookupK8sDaemonSetArgs, opts ...pulumi.InvokeOption) (*LookupK8sDaemonSetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupK8sDaemonSetResult
	err := ctx.Invoke("duplocloud:index/getK8sDaemonSet:getK8sDaemonSet", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getK8sDaemonSet.
type LookupK8sDaemonSetArgs struct {
	// Standard daemonset's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata GetK8sDaemonSetMetadata `pulumi:"metadata"`
	// The GUID of the tenant that the DaemonSet will be created in.
	TenantId string `pulumi:"tenantId"`
}

// A collection of values returned by getK8sDaemonSet.
type LookupK8sDaemonSetResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// When true, the DaemonSet will be deployed only to the tenant's nodes. When false, it is deployed cluster-wide (requires the tenant to have the CAN*DEPLOY*CLUSTER*WIDE*DAEMONSET metadata enabled).
	IsTenantLocal bool `pulumi:"isTenantLocal"`
	// Standard daemonset's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata GetK8sDaemonSetMetadata `pulumi:"metadata"`
	// Spec of the DaemonSet.
	Specs []GetK8sDaemonSetSpec `pulumi:"specs"`
	// The GUID of the tenant that the DaemonSet will be created in.
	TenantId string `pulumi:"tenantId"`
}

func LookupK8sDaemonSetOutput(ctx *pulumi.Context, args LookupK8sDaemonSetOutputArgs, opts ...pulumi.InvokeOption) LookupK8sDaemonSetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupK8sDaemonSetResultOutput, error) {
			args := v.(LookupK8sDaemonSetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("duplocloud:index/getK8sDaemonSet:getK8sDaemonSet", args, LookupK8sDaemonSetResultOutput{}, options).(LookupK8sDaemonSetResultOutput), nil
		}).(LookupK8sDaemonSetResultOutput)
}

// A collection of arguments for invoking getK8sDaemonSet.
type LookupK8sDaemonSetOutputArgs struct {
	// Standard daemonset's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata GetK8sDaemonSetMetadataInput `pulumi:"metadata"`
	// The GUID of the tenant that the DaemonSet will be created in.
	TenantId pulumi.StringInput `pulumi:"tenantId"`
}

func (LookupK8sDaemonSetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupK8sDaemonSetArgs)(nil)).Elem()
}

// A collection of values returned by getK8sDaemonSet.
type LookupK8sDaemonSetResultOutput struct{ *pulumi.OutputState }

func (LookupK8sDaemonSetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupK8sDaemonSetResult)(nil)).Elem()
}

func (o LookupK8sDaemonSetResultOutput) ToLookupK8sDaemonSetResultOutput() LookupK8sDaemonSetResultOutput {
	return o
}

func (o LookupK8sDaemonSetResultOutput) ToLookupK8sDaemonSetResultOutputWithContext(ctx context.Context) LookupK8sDaemonSetResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupK8sDaemonSetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupK8sDaemonSetResult) string { return v.Id }).(pulumi.StringOutput)
}

// When true, the DaemonSet will be deployed only to the tenant's nodes. When false, it is deployed cluster-wide (requires the tenant to have the CAN*DEPLOY*CLUSTER*WIDE*DAEMONSET metadata enabled).
func (o LookupK8sDaemonSetResultOutput) IsTenantLocal() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupK8sDaemonSetResult) bool { return v.IsTenantLocal }).(pulumi.BoolOutput)
}

// Standard daemonset's metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
func (o LookupK8sDaemonSetResultOutput) Metadata() GetK8sDaemonSetMetadataOutput {
	return o.ApplyT(func(v LookupK8sDaemonSetResult) GetK8sDaemonSetMetadata { return v.Metadata }).(GetK8sDaemonSetMetadataOutput)
}

// Spec of the DaemonSet.
func (o LookupK8sDaemonSetResultOutput) Specs() GetK8sDaemonSetSpecArrayOutput {
	return o.ApplyT(func(v LookupK8sDaemonSetResult) []GetK8sDaemonSetSpec { return v.Specs }).(GetK8sDaemonSetSpecArrayOutput)
}

// The GUID of the tenant that the DaemonSet will be created in.
func (o LookupK8sDaemonSetResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupK8sDaemonSetResult) string { return v.TenantId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupK8sDaemonSetResultOutput{})
}
