// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class AwsCloudfrontDistributionV2Restrictions
    {
        public readonly Outputs.AwsCloudfrontDistributionV2RestrictionsGeoRestriction GeoRestriction;

        [OutputConstructor]
        private AwsCloudfrontDistributionV2Restrictions(Outputs.AwsCloudfrontDistributionV2RestrictionsGeoRestriction geoRestriction)
        {
            GeoRestriction = geoRestriction;
        }
    }
}
