// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Outputs
{

    [OutputType]
    public sealed class AwsCloudfrontDistributionDefaultCacheBehaviorForwardedValues
    {
        public readonly Outputs.AwsCloudfrontDistributionDefaultCacheBehaviorForwardedValuesCookies Cookies;
        /// <summary>
        /// headers: Not required when cache*policy*id is set
        /// </summary>
        public readonly ImmutableArray<string> Headers;
        public readonly bool QueryString;
        /// <summary>
        /// query*string*cache*keys: Not required when cache*policy_id is set
        /// </summary>
        public readonly ImmutableArray<string> QueryStringCacheKeys;

        [OutputConstructor]
        private AwsCloudfrontDistributionDefaultCacheBehaviorForwardedValues(
            Outputs.AwsCloudfrontDistributionDefaultCacheBehaviorForwardedValuesCookies cookies,

            ImmutableArray<string> headers,

            bool queryString,

            ImmutableArray<string> queryStringCacheKeys)
        {
            Cookies = cookies;
            Headers = headers;
            QueryString = queryString;
            QueryStringCacheKeys = queryStringCacheKeys;
        }
    }
}
