// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class AzureCosmosDbAccountGeoLocation
    {
        /// <summary>
        /// The failover priority of the region. A failover priority of 0 indicates a write region. The maximum value for a failover priority = (total number of regions - 1). Failover priority values must be unique for each of the regions in which the database account exists. Changing this causes the location to be re-provisioned and cannot be changed for the location with failover priority 0
        /// </summary>
        public readonly int FailoverPriority;
        /// <summary>
        /// Should zone redundancy be enabled for this region? Defaults to `false`.
        /// </summary>
        public readonly bool? IsZoneRedundant;
        /// <summary>
        /// The name of the Azure region to host replicated data
        /// </summary>
        public readonly string LocationName;

        [OutputConstructor]
        private AzureCosmosDbAccountGeoLocation(
            int failoverPriority,

            bool? isZoneRedundant,

            string locationName)
        {
            FailoverPriority = failoverPriority;
            IsZoneRedundant = isZoneRedundant;
            LocationName = locationName;
        }
    }
}
