// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class GcpPubsubSubscriptionBigQuery
    {
        /// <summary>
        /// When true and use*topic*schema or use*table*schema is true, any fields that are a part of the topic schema or message schema that are not part of the BigQuery table schema are dropped when writing to BigQuery. Otherwise, the schemas must be kept in sync and any messages with extra fields are not written and remain in the subscription's backlog Defaults to `false`.
        /// </summary>
        public readonly bool? DropUnknownFields;
        /// <summary>
        /// The service account to use to write to BigQuery. If not specified, the Pub/Sub service agent, service-{project_number}@gcp-sa-pubsub.iam.gserviceaccount.com, is used.
        /// </summary>
        public readonly string? ServiceAccountEmail;
        /// <summary>
        /// An output-only field that indicates whether or not the subscription can receive messages.
        /// </summary>
        public readonly string? State;
        /// <summary>
        /// The name of the table to which to write data.
        /// </summary>
        public readonly string Table;
        /// <summary>
        /// When true, write the subscription name, messageId, publishTime, attributes, and orderingKey to additional columns in the table. Defaults to `false`.
        /// </summary>
        public readonly bool? UseTableSchema;
        /// <summary>
        /// When true, use the topic's schema as the columns to write to in BigQuery, if it exists. Only one of use*topic*schema and use*table*schema can be set. Defaults to `false`.
        /// </summary>
        public readonly bool? UseTopicSchema;
        /// <summary>
        /// When true, write the subscription name, messageId, publishTime, attributes, and orderingKey as additional fields in the output. Defaults to `false`.
        /// </summary>
        public readonly bool? WriteMetadata;

        [OutputConstructor]
        private GcpPubsubSubscriptionBigQuery(
            bool? dropUnknownFields,

            string? serviceAccountEmail,

            string? state,

            string table,

            bool? useTableSchema,

            bool? useTopicSchema,

            bool? writeMetadata)
        {
            DropUnknownFields = dropUnknownFields;
            ServiceAccountEmail = serviceAccountEmail;
            State = state;
            Table = table;
            UseTableSchema = useTableSchema;
            UseTopicSchema = useTopicSchema;
            WriteMetadata = writeMetadata;
        }
    }
}
