// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetAzureCosmosDbAccountConsistencyPolicyResult
    {
        /// <summary>
        /// Specify the default consistency level and configuration settings of the Cosmos DB account. Possible values include: 'Eventual', 'Session', 'BoundedStaleness','Strong', 'ConsistentPrefix'
        /// </summary>
        public readonly string DefaultConsistencyLevel;
        /// <summary>
        /// Max amount of time staleness (in seconds) is tolerated
        /// </summary>
        public readonly int MaxIntervalInSeconds;
        /// <summary>
        /// Max number of stale requests tolerated. Accepted range for this values 1 to 2147483647
        /// </summary>
        public readonly int MaxStalenessPrefix;

        [OutputConstructor]
        private GetAzureCosmosDbAccountConsistencyPolicyResult(
            string defaultConsistencyLevel,

            int maxIntervalInSeconds,

            int maxStalenessPrefix)
        {
            DefaultConsistencyLevel = defaultConsistencyLevel;
            MaxIntervalInSeconds = maxIntervalInSeconds;
            MaxStalenessPrefix = maxStalenessPrefix;
        }
    }
}
