// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetAwsSsmParametersParameterResult
    {
        public readonly string AllowedPattern;
        public readonly string Description;
        public readonly string KeyId;
        public readonly string LastModifiedDate;
        public readonly string LastModifiedUser;
        public readonly string Name;
        public readonly string TenantId;
        public readonly string Type;

        [OutputConstructor]
        private GetAwsSsmParametersParameterResult(
            string allowedPattern,

            string description,

            string keyId,

            string lastModifiedDate,

            string lastModifiedUser,

            string name,

            string tenantId,

            string type)
        {
            AllowedPattern = allowedPattern;
            Description = description;
            KeyId = keyId;
            LastModifiedDate = lastModifiedDate;
            LastModifiedUser = lastModifiedUser;
            Name = name;
            TenantId = tenantId;
            Type = type;
        }
    }
}
