// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetDuploServicesServiceResult
    {
        public readonly int AgentPlatform;
        public readonly string AllocationTags;
        public readonly bool AnyHostAllowed;
        public readonly int Cloud;
        public readonly bool CloudCredsFromK8sServiceAccount;
        public readonly ImmutableArray<string> Commands;
        public readonly string DockerImage;
        /// <summary>
        /// The service domain (whichever fqdn_ex or fqdn which is non empty)
        /// </summary>
        public readonly string Domain;
        public readonly string ExtraConfig;
        public readonly bool ForceStatefulSet;
        /// <summary>
        /// The fully qualified domain associated with the service
        /// </summary>
        public readonly string Fqdn;
        /// <summary>
        /// External fully qualified domain associated with the service
        /// </summary>
        public readonly string FqdnEx;
        public readonly string HpaSpecs;
        public readonly bool IsDaemonset;
        /// <summary>
        /// Whether or not the replicas must be scheduled on separate Kubernetes nodes.  Only supported on Kubernetes.
        /// </summary>
        public readonly bool IsUniqueK8sNodeRequired;
        public readonly bool LbSyncedDeployment;
        public readonly string Name;
        public readonly string OtherDockerConfig;
        public readonly string OtherDockerHostConfig;
        /// <summary>
        /// The service's parent domain
        /// </summary>
        public readonly string ParentDomain;
        public readonly bool ReplicaCollocationAllowed;
        public readonly int Replicas;
        public readonly string ReplicasMatchingAsgName;
        /// <summary>
        /// Whether or not the replicas must be spread across availability zones.  Only supported on Kubernetes.
        /// </summary>
        public readonly bool ShouldSpreadAcrossZones;
        public readonly ImmutableArray<Outputs.GetDuploServicesServiceTagResult> Tags;
        public readonly string TenantId;
        public readonly string Volumes;

        [OutputConstructor]
        private GetDuploServicesServiceResult(
            int agentPlatform,

            string allocationTags,

            bool anyHostAllowed,

            int cloud,

            bool cloudCredsFromK8sServiceAccount,

            ImmutableArray<string> commands,

            string dockerImage,

            string domain,

            string extraConfig,

            bool forceStatefulSet,

            string fqdn,

            string fqdnEx,

            string hpaSpecs,

            bool isDaemonset,

            bool isUniqueK8sNodeRequired,

            bool lbSyncedDeployment,

            string name,

            string otherDockerConfig,

            string otherDockerHostConfig,

            string parentDomain,

            bool replicaCollocationAllowed,

            int replicas,

            string replicasMatchingAsgName,

            bool shouldSpreadAcrossZones,

            ImmutableArray<Outputs.GetDuploServicesServiceTagResult> tags,

            string tenantId,

            string volumes)
        {
            AgentPlatform = agentPlatform;
            AllocationTags = allocationTags;
            AnyHostAllowed = anyHostAllowed;
            Cloud = cloud;
            CloudCredsFromK8sServiceAccount = cloudCredsFromK8sServiceAccount;
            Commands = commands;
            DockerImage = dockerImage;
            Domain = domain;
            ExtraConfig = extraConfig;
            ForceStatefulSet = forceStatefulSet;
            Fqdn = fqdn;
            FqdnEx = fqdnEx;
            HpaSpecs = hpaSpecs;
            IsDaemonset = isDaemonset;
            IsUniqueK8sNodeRequired = isUniqueK8sNodeRequired;
            LbSyncedDeployment = lbSyncedDeployment;
            Name = name;
            OtherDockerConfig = otherDockerConfig;
            OtherDockerHostConfig = otherDockerHostConfig;
            ParentDomain = parentDomain;
            ReplicaCollocationAllowed = replicaCollocationAllowed;
            Replicas = replicas;
            ReplicasMatchingAsgName = replicasMatchingAsgName;
            ShouldSpreadAcrossZones = shouldSpreadAcrossZones;
            Tags = tags;
            TenantId = tenantId;
            Volumes = volumes;
        }
    }
}
