// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetGcpSqlDatabaseInstancesDatabaseResult
    {
        /// <summary>
        /// Connection name  of the database.
        /// </summary>
        public readonly string ConnectionName;
        /// <summary>
        /// The MySQL, PostgreSQL orSQL Server version to use.Supported values include `MYSQL_5_6`,`MYSQL_5_7`, `MYSQL_8_0`, `POSTGRES_9_6`,`POSTGRES_10`,`POSTGRES_11`,`POSTGRES_12`, `POSTGRES_13`, `POSTGRES_14`, `POSTGRES_15`, `SQLSERVER_2017_STANDARD`,`SQLSERVER_2017_ENTERPRISE`,`SQLSERVER_2017_EXPRESS`, `SQLSERVER_2017_WEB`.`SQLSERVER_2019_STANDARD`, `SQLSERVER_2019_ENTERPRISE`, `SQLSERVER_2019_EXPRESS`,`SQLSERVER_2019_WEB`.[Database Version Policies](https://cloud.google.com/sql/docs/db-versions)includes an up-to-date reference of supported versions.
        /// </summary>
        public readonly string DatabaseVersion;
        /// <summary>
        /// The size of data disk, in GB. Size of a running instance cannot be reduced but can be increased. The minimum value is 10GB.
        /// </summary>
        public readonly int DiskSize;
        /// <summary>
        /// IP address of the database.
        /// </summary>
        public readonly ImmutableArray<string> IpAddresses;
        /// <summary>
        /// Map of string keys and values that can be used to organize and categorize this resource.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Labels;
        /// <summary>
        /// The name of the sql database.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The SelfLink of the sql database.
        /// </summary>
        public readonly string SelfLink;
        /// <summary>
        /// The machine type to use. See tiers for more details and supported versions. Postgres supports only shared-core machine types, and custom machine types such as `db-custom-2-13312`.See the [Custom Machine Type Documentation](https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#create) to learn about specifying custom machine types.
        /// </summary>
        public readonly string Tier;

        [OutputConstructor]
        private GetGcpSqlDatabaseInstancesDatabaseResult(
            string connectionName,

            string databaseVersion,

            int diskSize,

            ImmutableArray<string> ipAddresses,

            ImmutableDictionary<string, string> labels,

            string name,

            string selfLink,

            string tier)
        {
            ConnectionName = connectionName;
            DatabaseVersion = databaseVersion;
            DiskSize = diskSize;
            IpAddresses = ipAddresses;
            Labels = labels;
            Name = name;
            SelfLink = selfLink;
            Tier = tier;
        }
    }
}
