// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetK8sJobSpecTemplateSpecInitContainerEnvFromResult
    {
        /// <summary>
        /// The ConfigMap to select from
        /// </summary>
        public readonly Outputs.GetK8sJobSpecTemplateSpecInitContainerEnvFromConfigMapRefResult? ConfigMapRef;
        /// <summary>
        /// An optional identifer to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
        /// </summary>
        public readonly string? Prefix;
        /// <summary>
        /// The Secret to select from
        /// </summary>
        public readonly Outputs.GetK8sJobSpecTemplateSpecInitContainerEnvFromSecretRefResult? SecretRef;

        [OutputConstructor]
        private GetK8sJobSpecTemplateSpecInitContainerEnvFromResult(
            Outputs.GetK8sJobSpecTemplateSpecInitContainerEnvFromConfigMapRefResult? configMapRef,

            string? prefix,

            Outputs.GetK8sJobSpecTemplateSpecInitContainerEnvFromSecretRefResult? secretRef)
        {
            ConfigMapRef = configMapRef;
            Prefix = prefix;
            SecretRef = secretRef;
        }
    }
}
