# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AwsCloudfrontFunctionArgs', 'AwsCloudfrontFunction']

@pulumi.input_type
class AwsCloudfrontFunctionArgs:
    def __init__(__self__, *,
                 code: pulumi.Input[str],
                 runtime: pulumi.Input[str],
                 tenant_id: pulumi.Input[str],
                 comment: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 publish: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a AwsCloudfrontFunction resource.
        :param pulumi.Input[str] code: The JavaScript code for the CloudFront function.
        :param pulumi.Input[str] runtime: The runtime environment for the CloudFront function.
        :param pulumi.Input[str] tenant_id: The GUID of the tenant in DuploCloud.
        :param pulumi.Input[str] comment: A comment to describe the CloudFront function.
        :param pulumi.Input[str] name: The name of the CloudFront function.
        :param pulumi.Input[bool] publish: Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
        """
        pulumi.set(__self__, "code", code)
        pulumi.set(__self__, "runtime", runtime)
        pulumi.set(__self__, "tenant_id", tenant_id)
        if comment is not None:
            pulumi.set(__self__, "comment", comment)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if publish is not None:
            pulumi.set(__self__, "publish", publish)

    @property
    @pulumi.getter
    def code(self) -> pulumi.Input[str]:
        """
        The JavaScript code for the CloudFront function.
        """
        return pulumi.get(self, "code")

    @code.setter
    def code(self, value: pulumi.Input[str]):
        pulumi.set(self, "code", value)

    @property
    @pulumi.getter
    def runtime(self) -> pulumi.Input[str]:
        """
        The runtime environment for the CloudFront function.
        """
        return pulumi.get(self, "runtime")

    @runtime.setter
    def runtime(self, value: pulumi.Input[str]):
        pulumi.set(self, "runtime", value)

    @property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Input[str]:
        """
        The GUID of the tenant in DuploCloud.
        """
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "tenant_id", value)

    @property
    @pulumi.getter
    def comment(self) -> Optional[pulumi.Input[str]]:
        """
        A comment to describe the CloudFront function.
        """
        return pulumi.get(self, "comment")

    @comment.setter
    def comment(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "comment", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the CloudFront function.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def publish(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
        """
        return pulumi.get(self, "publish")

    @publish.setter
    def publish(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "publish", value)


@pulumi.input_type
class _AwsCloudfrontFunctionState:
    def __init__(__self__, *,
                 code: Optional[pulumi.Input[str]] = None,
                 comment: Optional[pulumi.Input[str]] = None,
                 function_arn: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 publish: Optional[pulumi.Input[bool]] = None,
                 runtime: Optional[pulumi.Input[str]] = None,
                 status: Optional[pulumi.Input[str]] = None,
                 tenant_id: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering AwsCloudfrontFunction resources.
        :param pulumi.Input[str] code: The JavaScript code for the CloudFront function.
        :param pulumi.Input[str] comment: A comment to describe the CloudFront function.
        :param pulumi.Input[str] function_arn: The ARN of the CloudFront function.
        :param pulumi.Input[str] name: The name of the CloudFront function.
        :param pulumi.Input[bool] publish: Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
        :param pulumi.Input[str] runtime: The runtime environment for the CloudFront function.
        :param pulumi.Input[str] tenant_id: The GUID of the tenant in DuploCloud.
        """
        if code is not None:
            pulumi.set(__self__, "code", code)
        if comment is not None:
            pulumi.set(__self__, "comment", comment)
        if function_arn is not None:
            pulumi.set(__self__, "function_arn", function_arn)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if publish is not None:
            pulumi.set(__self__, "publish", publish)
        if runtime is not None:
            pulumi.set(__self__, "runtime", runtime)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if tenant_id is not None:
            pulumi.set(__self__, "tenant_id", tenant_id)

    @property
    @pulumi.getter
    def code(self) -> Optional[pulumi.Input[str]]:
        """
        The JavaScript code for the CloudFront function.
        """
        return pulumi.get(self, "code")

    @code.setter
    def code(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "code", value)

    @property
    @pulumi.getter
    def comment(self) -> Optional[pulumi.Input[str]]:
        """
        A comment to describe the CloudFront function.
        """
        return pulumi.get(self, "comment")

    @comment.setter
    def comment(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "comment", value)

    @property
    @pulumi.getter(name="functionArn")
    def function_arn(self) -> Optional[pulumi.Input[str]]:
        """
        The ARN of the CloudFront function.
        """
        return pulumi.get(self, "function_arn")

    @function_arn.setter
    def function_arn(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "function_arn", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The name of the CloudFront function.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def publish(self) -> Optional[pulumi.Input[bool]]:
        """
        Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
        """
        return pulumi.get(self, "publish")

    @publish.setter
    def publish(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "publish", value)

    @property
    @pulumi.getter
    def runtime(self) -> Optional[pulumi.Input[str]]:
        """
        The runtime environment for the CloudFront function.
        """
        return pulumi.get(self, "runtime")

    @runtime.setter
    def runtime(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "runtime", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "status", value)

    @property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> Optional[pulumi.Input[str]]:
        """
        The GUID of the tenant in DuploCloud.
        """
        return pulumi.get(self, "tenant_id")

    @tenant_id.setter
    def tenant_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "tenant_id", value)


class AwsCloudfrontFunction(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 code: Optional[pulumi.Input[str]] = None,
                 comment: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 publish: Optional[pulumi.Input[bool]] = None,
                 runtime: Optional[pulumi.Input[str]] = None,
                 tenant_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        duplocloud_aws_cloudfront_function allows you to create and manage AWS CloudFront Functions in DuploCloud.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_duplocloud as duplocloud

        duplo_app = duplocloud.Tenant("duplo-app",
            account_name="duplo-app",
            plan_id="default")
        func = duplocloud.AwsCloudfrontFunction("func",
            tenant_id=duplo_app.tenant_id,
            name="test-cloudfront-func",
            runtime="cloudfront-js-2.0",
            code=\"\"\"function handler(event) {
          var request = event.request;
          var headers = request.headers;

          // Add a custom header
          headers['x-custom-header'] = { value: 'Hello from CloudFront Function!' };

          return request;     
        }
        \"\"\",
            comment="This is a test CloudFront function")
        ```

        ## Import

        Example: Importing an existing AWS Cloudfront Function

         - *TENANT_ID* is the tenant GUID

         - *SHORT_NAME* is the function name without duplo prefix

        # 

        ```sh
        $ pulumi import duplocloud:index/awsCloudfrontFunction:AwsCloudfrontFunction func *TENANT_ID*/cloudfront-function/*SHORT_NAME*
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] code: The JavaScript code for the CloudFront function.
        :param pulumi.Input[str] comment: A comment to describe the CloudFront function.
        :param pulumi.Input[str] name: The name of the CloudFront function.
        :param pulumi.Input[bool] publish: Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
        :param pulumi.Input[str] runtime: The runtime environment for the CloudFront function.
        :param pulumi.Input[str] tenant_id: The GUID of the tenant in DuploCloud.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AwsCloudfrontFunctionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        duplocloud_aws_cloudfront_function allows you to create and manage AWS CloudFront Functions in DuploCloud.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_duplocloud as duplocloud

        duplo_app = duplocloud.Tenant("duplo-app",
            account_name="duplo-app",
            plan_id="default")
        func = duplocloud.AwsCloudfrontFunction("func",
            tenant_id=duplo_app.tenant_id,
            name="test-cloudfront-func",
            runtime="cloudfront-js-2.0",
            code=\"\"\"function handler(event) {
          var request = event.request;
          var headers = request.headers;

          // Add a custom header
          headers['x-custom-header'] = { value: 'Hello from CloudFront Function!' };

          return request;     
        }
        \"\"\",
            comment="This is a test CloudFront function")
        ```

        ## Import

        Example: Importing an existing AWS Cloudfront Function

         - *TENANT_ID* is the tenant GUID

         - *SHORT_NAME* is the function name without duplo prefix

        # 

        ```sh
        $ pulumi import duplocloud:index/awsCloudfrontFunction:AwsCloudfrontFunction func *TENANT_ID*/cloudfront-function/*SHORT_NAME*
        ```

        :param str resource_name: The name of the resource.
        :param AwsCloudfrontFunctionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AwsCloudfrontFunctionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 code: Optional[pulumi.Input[str]] = None,
                 comment: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 publish: Optional[pulumi.Input[bool]] = None,
                 runtime: Optional[pulumi.Input[str]] = None,
                 tenant_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AwsCloudfrontFunctionArgs.__new__(AwsCloudfrontFunctionArgs)

            if code is None and not opts.urn:
                raise TypeError("Missing required property 'code'")
            __props__.__dict__["code"] = code
            __props__.__dict__["comment"] = comment
            __props__.__dict__["name"] = name
            __props__.__dict__["publish"] = publish
            if runtime is None and not opts.urn:
                raise TypeError("Missing required property 'runtime'")
            __props__.__dict__["runtime"] = runtime
            if tenant_id is None and not opts.urn:
                raise TypeError("Missing required property 'tenant_id'")
            __props__.__dict__["tenant_id"] = tenant_id
            __props__.__dict__["function_arn"] = None
            __props__.__dict__["status"] = None
        super(AwsCloudfrontFunction, __self__).__init__(
            'duplocloud:index/awsCloudfrontFunction:AwsCloudfrontFunction',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            code: Optional[pulumi.Input[str]] = None,
            comment: Optional[pulumi.Input[str]] = None,
            function_arn: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            publish: Optional[pulumi.Input[bool]] = None,
            runtime: Optional[pulumi.Input[str]] = None,
            status: Optional[pulumi.Input[str]] = None,
            tenant_id: Optional[pulumi.Input[str]] = None) -> 'AwsCloudfrontFunction':
        """
        Get an existing AwsCloudfrontFunction resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] code: The JavaScript code for the CloudFront function.
        :param pulumi.Input[str] comment: A comment to describe the CloudFront function.
        :param pulumi.Input[str] function_arn: The ARN of the CloudFront function.
        :param pulumi.Input[str] name: The name of the CloudFront function.
        :param pulumi.Input[bool] publish: Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
        :param pulumi.Input[str] runtime: The runtime environment for the CloudFront function.
        :param pulumi.Input[str] tenant_id: The GUID of the tenant in DuploCloud.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AwsCloudfrontFunctionState.__new__(_AwsCloudfrontFunctionState)

        __props__.__dict__["code"] = code
        __props__.__dict__["comment"] = comment
        __props__.__dict__["function_arn"] = function_arn
        __props__.__dict__["name"] = name
        __props__.__dict__["publish"] = publish
        __props__.__dict__["runtime"] = runtime
        __props__.__dict__["status"] = status
        __props__.__dict__["tenant_id"] = tenant_id
        return AwsCloudfrontFunction(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def code(self) -> pulumi.Output[str]:
        """
        The JavaScript code for the CloudFront function.
        """
        return pulumi.get(self, "code")

    @property
    @pulumi.getter
    def comment(self) -> pulumi.Output[Optional[str]]:
        """
        A comment to describe the CloudFront function.
        """
        return pulumi.get(self, "comment")

    @property
    @pulumi.getter(name="functionArn")
    def function_arn(self) -> pulumi.Output[str]:
        """
        The ARN of the CloudFront function.
        """
        return pulumi.get(self, "function_arn")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The name of the CloudFront function.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def publish(self) -> pulumi.Output[Optional[bool]]:
        """
        Whether to publish creation/change as Live CloudFront Function Version Defaults to `true`.
        """
        return pulumi.get(self, "publish")

    @property
    @pulumi.getter
    def runtime(self) -> pulumi.Output[str]:
        """
        The runtime environment for the CloudFront function.
        """
        return pulumi.get(self, "runtime")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[str]:
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> pulumi.Output[str]:
        """
        The GUID of the tenant in DuploCloud.
        """
        return pulumi.get(self, "tenant_id")

