// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class AwsCloudfrontDistributionV2OriginGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defaults to `3`.
        /// </summary>
        [Input("connectionAttempts")]
        public Input<int>? ConnectionAttempts { get; set; }

        /// <summary>
        /// Defaults to `10`.
        /// </summary>
        [Input("connectionTimeout")]
        public Input<int>? ConnectionTimeout { get; set; }

        [Input("customHeaders")]
        private InputList<Inputs.AwsCloudfrontDistributionV2OriginCustomHeaderGetArgs>? _customHeaders;
        public InputList<Inputs.AwsCloudfrontDistributionV2OriginCustomHeaderGetArgs> CustomHeaders
        {
            get => _customHeaders ?? (_customHeaders = new InputList<Inputs.AwsCloudfrontDistributionV2OriginCustomHeaderGetArgs>());
            set => _customHeaders = value;
        }

        [Input("customOriginConfig")]
        public Input<Inputs.AwsCloudfrontDistributionV2OriginCustomOriginConfigGetArgs>? CustomOriginConfig { get; set; }

        [Input("domainName", required: true)]
        public Input<string> DomainName { get; set; } = null!;

        [Input("originId", required: true)]
        public Input<string> OriginId { get; set; } = null!;

        /// <summary>
        /// Defaults to ``.
        /// </summary>
        [Input("originPath")]
        public Input<string>? OriginPath { get; set; }

        [Input("originShield")]
        public Input<Inputs.AwsCloudfrontDistributionV2OriginOriginShieldGetArgs>? OriginShield { get; set; }

        public AwsCloudfrontDistributionV2OriginGetArgs()
        {
        }
        public static new AwsCloudfrontDistributionV2OriginGetArgs Empty => new AwsCloudfrontDistributionV2OriginGetArgs();
    }
}
