// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class AwsCloudfrontDistributionV2DefaultCacheBehaviorForwardedValuesCookiesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("forward", required: true)]
        public Input<string> Forward { get; set; } = null!;

        [Input("whitelistedNames")]
        private InputList<string>? _whitelistedNames;
        public InputList<string> WhitelistedNames
        {
            get => _whitelistedNames ?? (_whitelistedNames = new InputList<string>());
            set => _whitelistedNames = value;
        }

        public AwsCloudfrontDistributionV2DefaultCacheBehaviorForwardedValuesCookiesGetArgs()
        {
        }
        public static new AwsCloudfrontDistributionV2DefaultCacheBehaviorForwardedValuesCookiesGetArgs Empty => new AwsCloudfrontDistributionV2DefaultCacheBehaviorForwardedValuesCookiesGetArgs();
    }
}
