// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class AwsElasticsearchClusterConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("coldStorageOptions")]
        public Input<Inputs.AwsElasticsearchClusterConfigColdStorageOptionsArgs>? ColdStorageOptions { get; set; }

        /// <summary>
        /// Defaults to `0`.
        /// </summary>
        [Input("dedicatedMasterCount")]
        public Input<int>? DedicatedMasterCount { get; set; }

        /// <summary>
        /// Defaults to `false`.
        /// </summary>
        [Input("dedicatedMasterEnabled")]
        public Input<bool>? DedicatedMasterEnabled { get; set; }

        /// <summary>
        /// Defaults to `t2.small.search`.
        /// </summary>
        [Input("dedicatedMasterType")]
        public Input<string>? DedicatedMasterType { get; set; }

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Input("instanceCount")]
        public Input<int>? InstanceCount { get; set; }

        /// <summary>
        /// Supported instance types for elasticsearch domain https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html Defaults to `t2.small.search`.
        /// </summary>
        [Input("instanceType")]
        public Input<string>? InstanceType { get; set; }

        [Input("multiAzWithStandbyEnabled")]
        public Input<bool>? MultiAzWithStandbyEnabled { get; set; }

        [Input("warmCount")]
        public Input<int>? WarmCount { get; set; }

        [Input("warmEnabled")]
        public Input<bool>? WarmEnabled { get; set; }

        [Input("warmType")]
        public Input<string>? WarmType { get; set; }

        public AwsElasticsearchClusterConfigArgs()
        {
        }
        public static new AwsElasticsearchClusterConfigArgs Empty => new AwsElasticsearchClusterConfigArgs();
    }
}
