// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Inputs
{

    public sealed class AwsLbListenerRuleActionForwardStickinessArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The time period, in seconds, during which requests from a client should be routed to the same target group.
        /// </summary>
        [Input("duration", required: true)]
        public Input<int> Duration { get; set; } = null!;

        /// <summary>
        /// Indicates whether target group stickiness is enabled. Defaults to `false`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public AwsLbListenerRuleActionForwardStickinessArgs()
        {
        }
        public static new AwsLbListenerRuleActionForwardStickinessArgs Empty => new AwsLbListenerRuleActionForwardStickinessArgs();
    }
}
