// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class AwsLaunchTemplateInstanceRequirementsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedInstanceTypes")]
        private InputList<string>? _allowedInstanceTypes;
        public InputList<string> AllowedInstanceTypes
        {
            get => _allowedInstanceTypes ?? (_allowedInstanceTypes = new InputList<string>());
            set => _allowedInstanceTypes = value;
        }

        [Input("cpuManufacturers")]
        private InputList<string>? _cpuManufacturers;

        /// <summary>
        /// List of CPU manufacturers (e.g. `intel`, `amd`, `amazon-web-services`).
        /// </summary>
        public InputList<string> CpuManufacturers
        {
            get => _cpuManufacturers ?? (_cpuManufacturers = new InputList<string>());
            set => _cpuManufacturers = value;
        }

        [Input("excludedInstanceTypes")]
        private InputList<string>? _excludedInstanceTypes;

        /// <summary>
        /// List of excluded instance types. Mutually exclusive with `allowed_instance_types`.
        /// </summary>
        public InputList<string> ExcludedInstanceTypes
        {
            get => _excludedInstanceTypes ?? (_excludedInstanceTypes = new InputList<string>());
            set => _excludedInstanceTypes = value;
        }

        [Input("instanceGenerations")]
        private InputList<string>? _instanceGenerations;

        /// <summary>
        /// List of instance generations (e.g. `current`, `previous`).
        /// </summary>
        public InputList<string> InstanceGenerations
        {
            get => _instanceGenerations ?? (_instanceGenerations = new InputList<string>());
            set => _instanceGenerations = value;
        }

        /// <summary>
        /// Block describing the minimum and maximum amount of memory (MiB). It is a required field when allowed*instance*types is set
        /// </summary>
        [Input("memoryMib")]
        public Input<Inputs.AwsLaunchTemplateInstanceRequirementsMemoryMibGetArgs>? MemoryMib { get; set; }

        /// <summary>
        /// Price protection threshold as a percentage over the lowest price.
        /// </summary>
        [Input("spotMaxPricePercentageOverLowestPrice")]
        public Input<int>? SpotMaxPricePercentageOverLowestPrice { get; set; }

        /// <summary>
        /// Block describing the minimum and maximum number of vCPUs. It is a required field when allowed*instance*types is set
        /// </summary>
        [Input("vcpuCount")]
        public Input<Inputs.AwsLaunchTemplateInstanceRequirementsVcpuCountGetArgs>? VcpuCount { get; set; }

        public AwsLaunchTemplateInstanceRequirementsGetArgs()
        {
        }
        public static new AwsLaunchTemplateInstanceRequirementsGetArgs Empty => new AwsLaunchTemplateInstanceRequirementsGetArgs();
    }
}
