// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Inputs
{

    public sealed class AwsLambdaFunctionDeadLetterConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ARN of an SNS topic or SQS queue to notify when an invocation fails.
        /// </summary>
        [Input("targetArn")]
        public Input<string>? TargetArn { get; set; }

        public AwsLambdaFunctionDeadLetterConfigArgs()
        {
        }
        public static new AwsLambdaFunctionDeadLetterConfigArgs Empty => new AwsLambdaFunctionDeadLetterConfigArgs();
    }
}
