// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Inputs
{

    public sealed class EcsServiceCapacityProviderStrategyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of tasks, at a minimum, to run on the specified capacity provider.
        /// </summary>
        [Input("base")]
        public Input<int>? Base { get; set; }

        /// <summary>
        /// Name of the capacity provider.
        /// </summary>
        [Input("capacityProvider", required: true)]
        public Input<string> CapacityProvider { get; set; } = null!;

        /// <summary>
        /// The relative percentage of the total number of launched tasks that should use the specified capacity provider.
        /// </summary>
        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public EcsServiceCapacityProviderStrategyGetArgs()
        {
        }
        public static new EcsServiceCapacityProviderStrategyGetArgs Empty => new EcsServiceCapacityProviderStrategyGetArgs();
    }
}
