// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class GcpInfraMaintenanceWindowRecurringWindowArgs : global::Pulumi.ResourceArgs
    {
        [Input("endTime", required: true)]
        public Input<string> EndTime { get; set; } = null!;

        /// <summary>
        /// Specify recurrence in RFC5545 RRULE format, to specify when this recurs.
        /// </summary>
        [Input("recurrence", required: true)]
        public Input<string> Recurrence { get; set; } = null!;

        [Input("startTime", required: true)]
        public Input<string> StartTime { get; set; } = null!;

        public GcpInfraMaintenanceWindowRecurringWindowArgs()
        {
        }
        public static new GcpInfraMaintenanceWindowRecurringWindowArgs Empty => new GcpInfraMaintenanceWindowRecurringWindowArgs();
    }
}
