// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class GcpStorageBucketV2DefaultEncryptionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Default encryption method.  Must be one of: `None`, `Sse`, `AwsKms`, `TenantKms`. Defaults to `Sse`.
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        public GcpStorageBucketV2DefaultEncryptionArgs()
        {
        }
        public static new GcpStorageBucketV2DefaultEncryptionArgs Empty => new GcpStorageBucketV2DefaultEncryptionArgs();
    }
}
