// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Inputs
{

    public sealed class GetGcpNodePoolAcceleratorGpuSharingConfigInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The configuration for GPU sharing options.
        /// </summary>
        [Input("gpuSharingStrategy", required: true)]
        public Input<string> GpuSharingStrategy { get; set; } = null!;

        /// <summary>
        /// The max number of containers that can share a physical GPU.
        /// </summary>
        [Input("maxSharedClientsPerGpu", required: true)]
        public Input<string> MaxSharedClientsPerGpu { get; set; } = null!;

        public GetGcpNodePoolAcceleratorGpuSharingConfigInputArgs()
        {
        }
        public static new GetGcpNodePoolAcceleratorGpuSharingConfigInputArgs Empty => new GetGcpNodePoolAcceleratorGpuSharingConfigInputArgs();
    }
}
