// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class K8IngressLbconfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ARN of an ACM certificate to associate with this load balancer.  Only applicable for HTTPS.
        /// </summary>
        [Input("certificateArn")]
        public Input<string>? CertificateArn { get; set; }

        /// <summary>
        /// The DNS prefix to expose services using Route53 domain.
        /// </summary>
        [Input("dnsPrefix", required: true)]
        public Input<string> DnsPrefix { get; set; } = null!;

        /// <summary>
        /// HTTP Listener Port.
        /// </summary>
        [Input("httpPort")]
        public Input<int>? HttpPort { get; set; }

        /// <summary>
        /// HTTPS Listener Port.
        /// </summary>
        [Input("httpsPort")]
        public Input<int>? HttpsPort { get; set; }

        /// <summary>
        /// Whether or not to create an internal load balancer.
        /// </summary>
        [Input("isInternal", required: true)]
        public Input<bool> IsInternal { get; set; } = null!;

        public K8IngressLbconfigArgs()
        {
        }
        public static new K8IngressLbconfigArgs Empty => new K8IngressLbconfigArgs();
    }
}
