// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Inputs
{

    public sealed class K8sCronJobSpecJobTemplateSpecTemplateSpecVolumeConfigMapGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set. Defaults to `0644`.
        /// </summary>
        [Input("defaultMode")]
        public Input<string>? DefaultMode { get; set; }

        [Input("items")]
        private InputList<Inputs.K8sCronJobSpecJobTemplateSpecTemplateSpecVolumeConfigMapItemGetArgs>? _items;

        /// <summary>
        /// If unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'.
        /// </summary>
        public InputList<Inputs.K8sCronJobSpecJobTemplateSpecTemplateSpecVolumeConfigMapItemGetArgs> Items
        {
            get => _items ?? (_items = new InputList<Inputs.K8sCronJobSpecJobTemplateSpecTemplateSpecVolumeConfigMapItemGetArgs>());
            set => _items = value;
        }

        /// <summary>
        /// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Optional: Specify whether the ConfigMap or its keys must be defined.
        /// </summary>
        [Input("optional")]
        public Input<bool>? Optional { get; set; }

        public K8sCronJobSpecJobTemplateSpecTemplateSpecVolumeConfigMapGetArgs()
        {
        }
        public static new K8sCronJobSpecJobTemplateSpecTemplateSpecVolumeConfigMapGetArgs Empty => new K8sCronJobSpecJobTemplateSpecTemplateSpecVolumeConfigMapGetArgs();
    }
}
