// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class K8sCronJobSpecJobTemplateSpecTemplateSpecContainerEnvValueFromResourceFieldRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("containerName")]
        public Input<string>? ContainerName { get; set; }

        /// <summary>
        /// Defaults to `1`.
        /// </summary>
        [Input("divisor")]
        public Input<string>? Divisor { get; set; }

        /// <summary>
        /// Resource to select
        /// </summary>
        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        public K8sCronJobSpecJobTemplateSpecTemplateSpecContainerEnvValueFromResourceFieldRefArgs()
        {
        }
        public static new K8sCronJobSpecJobTemplateSpecTemplateSpecContainerEnvValueFromResourceFieldRefArgs Empty => new K8sCronJobSpecJobTemplateSpecTemplateSpecContainerEnvValueFromResourceFieldRefArgs();
    }
}
