// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class K8sDaemonSetSpecTemplateSpecVolumeProjectedSourceDownwardApiItemGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Selects a field of the pod: only annotations, labels, name and namespace are supported.
        /// </summary>
        [Input("fieldRef")]
        public Input<Inputs.K8sDaemonSetSpecTemplateSpecVolumeProjectedSourceDownwardApiItemFieldRefGetArgs>? FieldRef { get; set; }

        /// <summary>
        /// Mode bits to use on this file, must be a value between 0 and 0777. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        /// <summary>
        /// Path is the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, requests.cpu and requests.memory) are currently supported.
        /// </summary>
        [Input("resourceFieldRef")]
        public Input<Inputs.K8sDaemonSetSpecTemplateSpecVolumeProjectedSourceDownwardApiItemResourceFieldRefGetArgs>? ResourceFieldRef { get; set; }

        public K8sDaemonSetSpecTemplateSpecVolumeProjectedSourceDownwardApiItemGetArgs()
        {
        }
        public static new K8sDaemonSetSpecTemplateSpecVolumeProjectedSourceDownwardApiItemGetArgs Empty => new K8sDaemonSetSpecTemplateSpecVolumeProjectedSourceDownwardApiItemGetArgs();
    }
}
