// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class K8sDaemonSetSpecTemplateSpecVolumeQuobyteGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group to map volume access to Default is no group
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        /// <summary>
        /// Whether to force the Quobyte volume to be mounted with read-only permissions. Defaults to false.
        /// </summary>
        [Input("readOnly")]
        public Input<bool>? ReadOnly { get; set; }

        /// <summary>
        /// Registry represents a single or multiple Quobyte Registry services specified as a string as host:port pair (multiple entries are separated with commas) which acts as the central registry for volumes
        /// </summary>
        [Input("registry", required: true)]
        public Input<string> Registry { get; set; } = null!;

        /// <summary>
        /// User to map volume access to Defaults to serivceaccount user
        /// </summary>
        [Input("user")]
        public Input<string>? User { get; set; }

        /// <summary>
        /// Volume is a string that references an already created Quobyte volume by name.
        /// </summary>
        [Input("volume", required: true)]
        public Input<string> Volume { get; set; } = null!;

        public K8sDaemonSetSpecTemplateSpecVolumeQuobyteGetArgs()
        {
        }
        public static new K8sDaemonSetSpecTemplateSpecVolumeQuobyteGetArgs Empty => new K8sDaemonSetSpecTemplateSpecVolumeQuobyteGetArgs();
    }
}
