// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace DuploCloud.Pulumi.Inputs
{

    public sealed class K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// exec specifies the action to take.
        /// </summary>
        [Input("exec")]
        public Input<Inputs.K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopExecArgs>? Exec { get; set; }

        /// <summary>
        /// Specifies the http request to perform.
        /// </summary>
        [Input("httpGet")]
        public Input<Inputs.K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopHttpGetArgs>? HttpGet { get; set; }

        [Input("tcpSockets")]
        private InputList<Inputs.K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopTcpSocketArgs>? _tcpSockets;

        /// <summary>
        /// TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported
        /// </summary>
        public InputList<Inputs.K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopTcpSocketArgs> TcpSockets
        {
            get => _tcpSockets ?? (_tcpSockets = new InputList<Inputs.K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopTcpSocketArgs>());
            set => _tcpSockets = value;
        }

        public K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopArgs()
        {
        }
        public static new K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopArgs Empty => new K8sDaemonSetSpecTemplateSpecContainerLifecyclePreStopArgs();
    }
}
