// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Inputs
{

    public sealed class K8SecretProviderClassSecretObjectDataArgs : global::Pulumi.ResourceArgs
    {
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        [Input("objectName", required: true)]
        public Input<string> ObjectName { get; set; } = null!;

        public K8SecretProviderClassSecretObjectDataArgs()
        {
        }
        public static new K8SecretProviderClassSecretObjectDataArgs Empty => new K8SecretProviderClassSecretObjectDataArgs();
    }
}
