// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Duplocloud.Inputs
{

    public sealed class RdsInstanceV2ScalingConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies max scaling capacity.
        /// </summary>
        [Input("maxCapacity", required: true)]
        public Input<double> MaxCapacity { get; set; } = null!;

        /// <summary>
        /// Specifies min scaling capacity.
        /// </summary>
        [Input("minCapacity", required: true)]
        public Input<double> MinCapacity { get; set; } = null!;

        public RdsInstanceV2ScalingConfigurationArgs()
        {
        }
        public static new RdsInstanceV2ScalingConfigurationArgs Empty => new RdsInstanceV2ScalingConfigurationArgs();
    }
}
