// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * `duplocloud.AwsSqsQueue` manages a SQS queue in Duplo.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as duplocloud from "@pulumi/duplocloud";
 *
 * const myapp = new duplocloud.Tenant("myapp", {
 *     accountName: "myapp",
 *     planId: "default",
 * });
 * const sqsQueue = new duplocloud.AwsSqsQueue("sqs_queue", {
 *     tenantId: myapp.tenantId,
 *     name: "duplo_queue",
 *     fifoQueue: true,
 *     messageRetentionSeconds: 345600,
 *     visibilityTimeoutSeconds: 30,
 *     contentBasedDeduplication: true,
 *     delaySeconds: 10,
 * });
 * // SQS queue with dead letter queue configuration
 * const sqsQueueWithDlq = new duplocloud.AwsSqsQueue("sqs_queue_with_dlq", {
 *     tenantId: myapp.tenantId,
 *     name: "duplo_queue",
 *     fifoQueue: true,
 *     messageRetentionSeconds: 345600,
 *     visibilityTimeoutSeconds: 30,
 *     contentBasedDeduplication: true,
 *     delaySeconds: 10,
 *     deadLetterQueueConfiguration: {
 *         targetSqsDlqName: sqsQueue.fullname,
 *         maxMessageReceiveAttempts: 5,
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Example: Importing an existing AWS SQS Queue
 *
 *  - *TENANT_ID* is the tenant GUID
 *
 *  - *URL* The URL for the created Amazon SQS queue.
 *
 * # 
 *
 * ```sh
 * $ pulumi import duplocloud:index/awsSqsQueue:AwsSqsQueue sqs_queue *TENANT_ID*&#47;*URL*
 * ```
 */
export class AwsSqsQueue extends pulumi.CustomResource {
    /**
     * Get an existing AwsSqsQueue resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AwsSqsQueueState, opts?: pulumi.CustomResourceOptions): AwsSqsQueue {
        return new AwsSqsQueue(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'duplocloud:index/awsSqsQueue:AwsSqsQueue';

    /**
     * Returns true if the given object is an instance of AwsSqsQueue.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AwsSqsQueue {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AwsSqsQueue.__pulumiType;
    }

    /**
     * The ARN of the SQS queue.
     */
    public /*out*/ readonly arn!: pulumi.Output<string>;
    /**
     * Enables content-based deduplication for FIFO queues.
     */
    public readonly contentBasedDeduplication!: pulumi.Output<boolean>;
    /**
     * SQS configuration for the SQS resource
     */
    public readonly deadLetterQueueConfiguration!: pulumi.Output<outputs.AwsSqsQueueDeadLetterQueueConfiguration | undefined>;
    /**
     * Specifies whether message deduplication occurs at the message group or queue level. Valid values are `messageGroup` and `queue`.
     */
    public readonly deduplicationScope!: pulumi.Output<string>;
    /**
     * Postpone the delivery of new messages to consumers for a number of seconds seconds range [0-900]
     */
    public readonly delaySeconds!: pulumi.Output<number>;
    /**
     * Boolean designating a FIFO queue. If not set, it defaults to `false` making it standard.
     */
    public readonly fifoQueue!: pulumi.Output<boolean | undefined>;
    /**
     * Specifies whether the FIFO queue throughput quota applies to the entire queue or per message group. Valid values are `perQueue` (default) and `perMessageGroupId`.
     */
    public readonly fifoThroughputLimit!: pulumi.Output<string>;
    /**
     * The full name of the SQS queue.
     */
    public /*out*/ readonly fullname!: pulumi.Output<string>;
    /**
     * The number of seconds Amazon SQS retains a message. Integer representing seconds, from 60 (1 minute) to 1209600 (14 days).
     */
    public readonly messageRetentionSeconds!: pulumi.Output<number>;
    /**
     * The name of the queue. Queue names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and have up to 80 characters long which is inclusive of duplo prefix (duploservices-{tenant_name}-) appended by the system.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The GUID of the tenant that the SQS queue will be created in.
     */
    public readonly tenantId!: pulumi.Output<string>;
    /**
     * The URL for the created Amazon SQS queue.
     */
    public /*out*/ readonly url!: pulumi.Output<string>;
    /**
     * The visibility timeout for the queue. An integer from 0 to 43200 (12 hours).
     */
    public readonly visibilityTimeoutSeconds!: pulumi.Output<number>;

    /**
     * Create a AwsSqsQueue resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AwsSqsQueueArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AwsSqsQueueArgs | AwsSqsQueueState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AwsSqsQueueState | undefined;
            resourceInputs["arn"] = state ? state.arn : undefined;
            resourceInputs["contentBasedDeduplication"] = state ? state.contentBasedDeduplication : undefined;
            resourceInputs["deadLetterQueueConfiguration"] = state ? state.deadLetterQueueConfiguration : undefined;
            resourceInputs["deduplicationScope"] = state ? state.deduplicationScope : undefined;
            resourceInputs["delaySeconds"] = state ? state.delaySeconds : undefined;
            resourceInputs["fifoQueue"] = state ? state.fifoQueue : undefined;
            resourceInputs["fifoThroughputLimit"] = state ? state.fifoThroughputLimit : undefined;
            resourceInputs["fullname"] = state ? state.fullname : undefined;
            resourceInputs["messageRetentionSeconds"] = state ? state.messageRetentionSeconds : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["tenantId"] = state ? state.tenantId : undefined;
            resourceInputs["url"] = state ? state.url : undefined;
            resourceInputs["visibilityTimeoutSeconds"] = state ? state.visibilityTimeoutSeconds : undefined;
        } else {
            const args = argsOrState as AwsSqsQueueArgs | undefined;
            if ((!args || args.tenantId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'tenantId'");
            }
            resourceInputs["contentBasedDeduplication"] = args ? args.contentBasedDeduplication : undefined;
            resourceInputs["deadLetterQueueConfiguration"] = args ? args.deadLetterQueueConfiguration : undefined;
            resourceInputs["deduplicationScope"] = args ? args.deduplicationScope : undefined;
            resourceInputs["delaySeconds"] = args ? args.delaySeconds : undefined;
            resourceInputs["fifoQueue"] = args ? args.fifoQueue : undefined;
            resourceInputs["fifoThroughputLimit"] = args ? args.fifoThroughputLimit : undefined;
            resourceInputs["messageRetentionSeconds"] = args ? args.messageRetentionSeconds : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tenantId"] = args ? args.tenantId : undefined;
            resourceInputs["visibilityTimeoutSeconds"] = args ? args.visibilityTimeoutSeconds : undefined;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["fullname"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AwsSqsQueue.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AwsSqsQueue resources.
 */
export interface AwsSqsQueueState {
    /**
     * The ARN of the SQS queue.
     */
    arn?: pulumi.Input<string>;
    /**
     * Enables content-based deduplication for FIFO queues.
     */
    contentBasedDeduplication?: pulumi.Input<boolean>;
    /**
     * SQS configuration for the SQS resource
     */
    deadLetterQueueConfiguration?: pulumi.Input<inputs.AwsSqsQueueDeadLetterQueueConfiguration>;
    /**
     * Specifies whether message deduplication occurs at the message group or queue level. Valid values are `messageGroup` and `queue`.
     */
    deduplicationScope?: pulumi.Input<string>;
    /**
     * Postpone the delivery of new messages to consumers for a number of seconds seconds range [0-900]
     */
    delaySeconds?: pulumi.Input<number>;
    /**
     * Boolean designating a FIFO queue. If not set, it defaults to `false` making it standard.
     */
    fifoQueue?: pulumi.Input<boolean>;
    /**
     * Specifies whether the FIFO queue throughput quota applies to the entire queue or per message group. Valid values are `perQueue` (default) and `perMessageGroupId`.
     */
    fifoThroughputLimit?: pulumi.Input<string>;
    /**
     * The full name of the SQS queue.
     */
    fullname?: pulumi.Input<string>;
    /**
     * The number of seconds Amazon SQS retains a message. Integer representing seconds, from 60 (1 minute) to 1209600 (14 days).
     */
    messageRetentionSeconds?: pulumi.Input<number>;
    /**
     * The name of the queue. Queue names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and have up to 80 characters long which is inclusive of duplo prefix (duploservices-{tenant_name}-) appended by the system.
     */
    name?: pulumi.Input<string>;
    /**
     * The GUID of the tenant that the SQS queue will be created in.
     */
    tenantId?: pulumi.Input<string>;
    /**
     * The URL for the created Amazon SQS queue.
     */
    url?: pulumi.Input<string>;
    /**
     * The visibility timeout for the queue. An integer from 0 to 43200 (12 hours).
     */
    visibilityTimeoutSeconds?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a AwsSqsQueue resource.
 */
export interface AwsSqsQueueArgs {
    /**
     * Enables content-based deduplication for FIFO queues.
     */
    contentBasedDeduplication?: pulumi.Input<boolean>;
    /**
     * SQS configuration for the SQS resource
     */
    deadLetterQueueConfiguration?: pulumi.Input<inputs.AwsSqsQueueDeadLetterQueueConfiguration>;
    /**
     * Specifies whether message deduplication occurs at the message group or queue level. Valid values are `messageGroup` and `queue`.
     */
    deduplicationScope?: pulumi.Input<string>;
    /**
     * Postpone the delivery of new messages to consumers for a number of seconds seconds range [0-900]
     */
    delaySeconds?: pulumi.Input<number>;
    /**
     * Boolean designating a FIFO queue. If not set, it defaults to `false` making it standard.
     */
    fifoQueue?: pulumi.Input<boolean>;
    /**
     * Specifies whether the FIFO queue throughput quota applies to the entire queue or per message group. Valid values are `perQueue` (default) and `perMessageGroupId`.
     */
    fifoThroughputLimit?: pulumi.Input<string>;
    /**
     * The number of seconds Amazon SQS retains a message. Integer representing seconds, from 60 (1 minute) to 1209600 (14 days).
     */
    messageRetentionSeconds?: pulumi.Input<number>;
    /**
     * The name of the queue. Queue names must be made up of only uppercase and lowercase ASCII letters, numbers, underscores, and hyphens, and have up to 80 characters long which is inclusive of duplo prefix (duploservices-{tenant_name}-) appended by the system.
     */
    name?: pulumi.Input<string>;
    /**
     * The GUID of the tenant that the SQS queue will be created in.
     */
    tenantId: pulumi.Input<string>;
    /**
     * The visibility timeout for the queue. An integer from 0 to 43200 (12 hours).
     */
    visibilityTimeoutSeconds?: pulumi.Input<number>;
}
