// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAwsSsmParameter(args: GetAwsSsmParameterArgs, opts?: pulumi.InvokeOptions): Promise<GetAwsSsmParameterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("duplocloud:index/getAwsSsmParameter:getAwsSsmParameter", {
        "name": args.name,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAwsSsmParameter.
 */
export interface GetAwsSsmParameterArgs {
    name: string;
    tenantId: string;
}

/**
 * A collection of values returned by getAwsSsmParameter.
 */
export interface GetAwsSsmParameterResult {
    readonly allowedPattern: string;
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keyId: string;
    readonly lastModifiedDate: string;
    readonly lastModifiedUser: string;
    readonly name: string;
    readonly tenantId: string;
    readonly type: string;
    readonly value: string;
}
export function getAwsSsmParameterOutput(args: GetAwsSsmParameterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAwsSsmParameterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("duplocloud:index/getAwsSsmParameter:getAwsSsmParameter", {
        "name": args.name,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAwsSsmParameter.
 */
export interface GetAwsSsmParameterOutputArgs {
    name: pulumi.Input<string>;
    tenantId: pulumi.Input<string>;
}
