// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `duplocloud.AzureCosmosDbDatabase` manages a azure cosmos db database in Duplo.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as duplocloud from "@pulumi/duplocloud";
 *
 * const db = duplocloud.getAzureCosmosDbDatabase({
 *     tenantId: "tenant id",
 *     name: "cosmos db account name",
 *     accountName: "cosmos db account name",
 * });
 * export const out = {
 *     type: db.then(db => db.type),
 *     namespace: db.then(db => db.namespace),
 * };
 * ```
 */
export function getAzureCosmosDbDatabase(args: GetAzureCosmosDbDatabaseArgs, opts?: pulumi.InvokeOptions): Promise<GetAzureCosmosDbDatabaseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("duplocloud:index/getAzureCosmosDbDatabase:getAzureCosmosDbDatabase", {
        "accountName": args.accountName,
        "name": args.name,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAzureCosmosDbDatabase.
 */
export interface GetAzureCosmosDbDatabaseArgs {
    /**
     * Indicates on which account database will be created
     */
    accountName: string;
    /**
     * The name for Cosmsos DB database.
     */
    name: string;
    /**
     * The GUID of the tenant in which the Cosmos DB database will be created for specified account
     */
    tenantId: string;
}

/**
 * A collection of values returned by getAzureCosmosDbDatabase.
 */
export interface GetAzureCosmosDbDatabaseResult {
    /**
     * Indicates on which account database will be created
     */
    readonly accountName: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name for Cosmsos DB database.
     */
    readonly name: string;
    /**
     * The Azure resource provider namespace for Cosmos DB. Defaults to 'Microsoft.DocumentDB'. This value is typically not changed and identifies the resource type within Azure.
     */
    readonly namespace: string;
    /**
     * The GUID of the tenant in which the Cosmos DB database will be created for specified account
     */
    readonly tenantId: string;
    /**
     * Specifies the Cosmos DB account type.
     */
    readonly type: string;
}
/**
 * `duplocloud.AzureCosmosDbDatabase` manages a azure cosmos db database in Duplo.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as duplocloud from "@pulumi/duplocloud";
 *
 * const db = duplocloud.getAzureCosmosDbDatabase({
 *     tenantId: "tenant id",
 *     name: "cosmos db account name",
 *     accountName: "cosmos db account name",
 * });
 * export const out = {
 *     type: db.then(db => db.type),
 *     namespace: db.then(db => db.namespace),
 * };
 * ```
 */
export function getAzureCosmosDbDatabaseOutput(args: GetAzureCosmosDbDatabaseOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAzureCosmosDbDatabaseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("duplocloud:index/getAzureCosmosDbDatabase:getAzureCosmosDbDatabase", {
        "accountName": args.accountName,
        "name": args.name,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getAzureCosmosDbDatabase.
 */
export interface GetAzureCosmosDbDatabaseOutputArgs {
    /**
     * Indicates on which account database will be created
     */
    accountName: pulumi.Input<string>;
    /**
     * The name for Cosmsos DB database.
     */
    name: pulumi.Input<string>;
    /**
     * The GUID of the tenant in which the Cosmos DB database will be created for specified account
     */
    tenantId: pulumi.Input<string>;
}
