// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * `duplocloud.DuploServiceLbconfigs` retrieves load balancer configuration(s) for container-based service(s) in Duplo.
 *
 * NOTE: For Amazon ECS services, see the `duplocloud.getEcsServices` data source.
 */
export function getDuploServiceLbconfigs(args: GetDuploServiceLbconfigsArgs, opts?: pulumi.InvokeOptions): Promise<GetDuploServiceLbconfigsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("duplocloud:index/getDuploServiceLbconfigs:getDuploServiceLbconfigs", {
        "name": args.name,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDuploServiceLbconfigs.
 */
export interface GetDuploServiceLbconfigsArgs {
    /**
     * The name of the duplo service.
     */
    name?: string;
    /**
     * The GUID of the tenant that hosts the duplo service.
     */
    tenantId: string;
}

/**
 * A collection of values returned by getDuploServiceLbconfigs.
 */
export interface GetDuploServiceLbconfigsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The name of the duplo service.
     */
    readonly name?: string;
    readonly services: outputs.GetDuploServiceLbconfigsService[];
    /**
     * The GUID of the tenant that hosts the duplo service.
     */
    readonly tenantId: string;
}
/**
 * `duplocloud.DuploServiceLbconfigs` retrieves load balancer configuration(s) for container-based service(s) in Duplo.
 *
 * NOTE: For Amazon ECS services, see the `duplocloud.getEcsServices` data source.
 */
export function getDuploServiceLbconfigsOutput(args: GetDuploServiceLbconfigsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDuploServiceLbconfigsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("duplocloud:index/getDuploServiceLbconfigs:getDuploServiceLbconfigs", {
        "name": args.name,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDuploServiceLbconfigs.
 */
export interface GetDuploServiceLbconfigsOutputArgs {
    /**
     * The name of the duplo service.
     */
    name?: pulumi.Input<string>;
    /**
     * The GUID of the tenant that hosts the duplo service.
     */
    tenantId: pulumi.Input<string>;
}
