// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * `duplocloud.getPlanWafs` retrieves a list of wafs for a given plan.
 */
export function getPlanWafsV2(args: GetPlanWafsV2Args, opts?: pulumi.InvokeOptions): Promise<GetPlanWafsV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("duplocloud:index/getPlanWafsV2:getPlanWafsV2", {
        "planId": args.planId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPlanWafsV2.
 */
export interface GetPlanWafsV2Args {
    /**
     * The plan ID
     */
    planId: string;
}

/**
 * A collection of values returned by getPlanWafsV2.
 */
export interface GetPlanWafsV2Result {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The plan ID
     */
    readonly planId: string;
    /**
     * The list of wafs for this plan.
     */
    readonly wafs: outputs.GetPlanWafsV2Waf[];
}
/**
 * `duplocloud.getPlanWafs` retrieves a list of wafs for a given plan.
 */
export function getPlanWafsV2Output(args: GetPlanWafsV2OutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPlanWafsV2Result> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("duplocloud:index/getPlanWafsV2:getPlanWafsV2", {
        "planId": args.planId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPlanWafsV2.
 */
export interface GetPlanWafsV2OutputArgs {
    /**
     * The plan ID
     */
    planId: pulumi.Input<string>;
}
