// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTenantAwsKmsKey(args: GetTenantAwsKmsKeyArgs, opts?: pulumi.InvokeOptions): Promise<GetTenantAwsKmsKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("duplocloud:index/getTenantAwsKmsKey:getTenantAwsKmsKey", {
        "keyName": args.keyName,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantAwsKmsKey.
 */
export interface GetTenantAwsKmsKeyArgs {
    keyName?: string;
    tenantId: string;
}

/**
 * A collection of values returned by getTenantAwsKmsKey.
 */
export interface GetTenantAwsKmsKeyResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keyArn: string;
    readonly keyId: string;
    readonly keyName: string;
    readonly tenantId: string;
}
export function getTenantAwsKmsKeyOutput(args: GetTenantAwsKmsKeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTenantAwsKmsKeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("duplocloud:index/getTenantAwsKmsKey:getTenantAwsKmsKey", {
        "keyName": args.keyName,
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantAwsKmsKey.
 */
export interface GetTenantAwsKmsKeyOutputArgs {
    keyName?: pulumi.Input<string>;
    tenantId: pulumi.Input<string>;
}
