// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTenantAwsRegion(args: GetTenantAwsRegionArgs, opts?: pulumi.InvokeOptions): Promise<GetTenantAwsRegionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("duplocloud:index/getTenantAwsRegion:getTenantAwsRegion", {
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantAwsRegion.
 */
export interface GetTenantAwsRegionArgs {
    tenantId: string;
}

/**
 * A collection of values returned by getTenantAwsRegion.
 */
export interface GetTenantAwsRegionResult {
    readonly awsRegion: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly tenantId: string;
}
export function getTenantAwsRegionOutput(args: GetTenantAwsRegionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTenantAwsRegionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("duplocloud:index/getTenantAwsRegion:getTenantAwsRegion", {
        "tenantId": args.tenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantAwsRegion.
 */
export interface GetTenantAwsRegionOutputArgs {
    tenantId: pulumi.Input<string>;
}
