// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * `duplocloud.PlanCertificates` manages the list of certificates avaialble to a plan in Duplo.
 *
 * This resource allows you take control of individual plan certificates for a specific plan.
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import duplocloud:index/planCertificates:PlanCertificates myplan PLAN_ID
 * ```
 */
export class PlanCertificates extends pulumi.CustomResource {
    /**
     * Get an existing PlanCertificates resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PlanCertificatesState, opts?: pulumi.CustomResourceOptions): PlanCertificates {
        return new PlanCertificates(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'duplocloud:index/planCertificates:PlanCertificates';

    /**
     * Returns true if the given object is an instance of PlanCertificates.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PlanCertificates {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PlanCertificates.__pulumiType;
    }

    /**
     * A list of certificates to manage.
     */
    public readonly certificate!: pulumi.Output<outputs.PlanCertificatesCertificate[] | undefined>;
    /**
     * A complete list of certificates for this plan, even ones not being managed by this resource.
     */
    public /*out*/ readonly certificates!: pulumi.Output<outputs.PlanCertificatesCertificate[]>;
    /**
     * Whether or not this resource should delete any certificates not specified by this resource. **WARNING:**  It is not recommended to change the default value of `false`. Defaults to `false`.
     */
    public readonly deleteUnspecifiedCertificates!: pulumi.Output<boolean | undefined>;
    /**
     * The ID of the plan to configure.
     */
    public readonly planId!: pulumi.Output<string>;
    /**
     * A list of certificate names being managed by this resource.
     */
    public /*out*/ readonly specifiedCertificates!: pulumi.Output<string[]>;

    /**
     * Create a PlanCertificates resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PlanCertificatesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PlanCertificatesArgs | PlanCertificatesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PlanCertificatesState | undefined;
            resourceInputs["certificate"] = state ? state.certificate : undefined;
            resourceInputs["certificates"] = state ? state.certificates : undefined;
            resourceInputs["deleteUnspecifiedCertificates"] = state ? state.deleteUnspecifiedCertificates : undefined;
            resourceInputs["planId"] = state ? state.planId : undefined;
            resourceInputs["specifiedCertificates"] = state ? state.specifiedCertificates : undefined;
        } else {
            const args = argsOrState as PlanCertificatesArgs | undefined;
            if ((!args || args.planId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'planId'");
            }
            resourceInputs["certificate"] = args ? args.certificate : undefined;
            resourceInputs["deleteUnspecifiedCertificates"] = args ? args.deleteUnspecifiedCertificates : undefined;
            resourceInputs["planId"] = args ? args.planId : undefined;
            resourceInputs["certificates"] = undefined /*out*/;
            resourceInputs["specifiedCertificates"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PlanCertificates.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PlanCertificates resources.
 */
export interface PlanCertificatesState {
    /**
     * A list of certificates to manage.
     */
    certificate?: pulumi.Input<pulumi.Input<inputs.PlanCertificatesCertificate>[]>;
    /**
     * A complete list of certificates for this plan, even ones not being managed by this resource.
     */
    certificates?: pulumi.Input<pulumi.Input<inputs.PlanCertificatesCertificate>[]>;
    /**
     * Whether or not this resource should delete any certificates not specified by this resource. **WARNING:**  It is not recommended to change the default value of `false`. Defaults to `false`.
     */
    deleteUnspecifiedCertificates?: pulumi.Input<boolean>;
    /**
     * The ID of the plan to configure.
     */
    planId?: pulumi.Input<string>;
    /**
     * A list of certificate names being managed by this resource.
     */
    specifiedCertificates?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a PlanCertificates resource.
 */
export interface PlanCertificatesArgs {
    /**
     * A list of certificates to manage.
     */
    certificate?: pulumi.Input<pulumi.Input<inputs.PlanCertificatesCertificate>[]>;
    /**
     * Whether or not this resource should delete any certificates not specified by this resource. **WARNING:**  It is not recommended to change the default value of `false`. Defaults to `false`.
     */
    deleteUnspecifiedCertificates?: pulumi.Input<boolean>;
    /**
     * The ID of the plan to configure.
     */
    planId: pulumi.Input<string>;
}
